import assert from 'node:assert/strict';
import { spawn, spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync, readdirSync, rmSync } from 'node:fs';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { configDir, moveSession, readSeat, sourceLabel } from '../src/service.ts';
import { renderPlist } from '../src/service-control.ts';
import { WebSocket } from 'ws';
const scratch=mkdtempSync(path.join(tmpdir(),'.siso-ephemeral-service-unit.'));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const wait=async(fn)=>{for(let i=0;i<100;i++){if(await fn())return;await sleep(50);}throw Error('Timeout');};
let child;
try {
  assert.equal(configDir('claude-siso-3',scratch),path.join(scratch,'.config/claude-siso-3'));
  assert.throws(()=>configDir('unknown',scratch));
  const from=path.join(scratch,'from'),to=path.join(scratch,'to');
  mkdirSync(path.join(from,'projects','cwd','lab-session'),{recursive:true});
  writeFileSync(path.join(from,'projects','cwd','lab-session.jsonl'),'history');
  writeFileSync(path.join(from,'projects','cwd','lab-session','tool'),'sidecar');
  moveSession('lab-session',from,to);
  assert.equal(readFileSync(path.join(to,'projects','cwd','lab-session.jsonl'),'utf8'),'history');
  assert.equal(readFileSync(path.join(to,'projects','cwd','lab-session','tool'),'utf8'),'sidecar');
  assert.equal(existsSync(path.join(from,'projects','cwd','lab-session.jsonl')),false);
  assert.ok(readdirSync(path.join(from,'projects','cwd')).some(f=>f.startsWith('lab-session.jsonl.moved-')));
  assert.throws(()=>moveSession('../bad',from,to));
  assert.equal(sourceLabel('sk-ant-secret'),null);
  assert.equal(sourceLabel('ANTHROPIC_API_KEY'),'ANTHROPIC_API_KEY');
  const seat=path.join(scratch,'seat.json');
  writeFileSync(seat,JSON.stringify({name:'LAB',session:'lab-session',login_launcher:'claude'}));
  assert.equal(readSeat(seat,'LAB').session,'lab-session'); assert.throws(()=>readSeat(seat,'A0'));
  const plist=renderPlist({label:'com.siso.host-lab',name:'LAB',resume:'lab-session',cwd:scratch,seat,hosts:scratch,node:process.execPath,runner:'runner.ts'});
  assert.match(plist,/<key>KeepAlive<\/key><true\/>/);assert.match(plist,/<integer>5<\/integer>/);
  assert.ok(!plist.includes('ANTHROPIC_API_KEY'));
  const fake=path.join(scratch,'launchctl');
  writeFileSync(fake,'#!/bin/sh\n[ "$1" = "print" ] && exit 1\nprintf "%s\\n" "$1" >> "$AB_CALLS"\nexit 0\n',{mode:0o700});
  const control=path.resolve('services/host/bin/siso-host-service');
  const env={...process.env,AB_LAUNCHCTL:fake,AB_LAUNCH_AGENTS_DIR:path.join(scratch,'plists'),AB_HOSTS_DIR:path.join(scratch,'hosts'),AB_SEAT_FILE:seat,AB_CALLS:path.join(scratch,'calls')};
  assert.notEqual(spawnSync(control,['uninstall'],{env,encoding:'utf8'}).status,0,'must never default to live A0');
  for(const cmd of ['install','status','uninstall']) {
    const r=spawnSync(control,[cmd,'--label','com.siso.host-lab','--name','LAB','--resume','lab-session'],{env,encoding:'utf8'});
    assert.equal(r.status,0,r.stderr);
  }
  assert.match(readFileSync(env.AB_CALLS,'utf8'),/bootstrap\nbootout/);
  child=spawn(process.execPath,['--experimental-strip-types','--no-warnings',path.resolve('services/host/src/host.ts'),'--name','LAB','--resume','lab-session'],{cwd:scratch,env:{...process.env,AB_HOST_SDK:path.resolve('services/host/test/fake-sdk.mjs'),AB_HOSTS_DIR:env.AB_HOSTS_DIR,AB_SERVICE_NAME:'LAB',HERDR_ENV:'0'},stdio:['ignore','ignore','pipe']});
  let errors='';child.stderr.on('data',d=>errors+=d);
  const file=path.join(env.AB_HOSTS_DIR,'name-LAB.json');
  await wait(()=>{if(child.exitCode!==null)throw Error(errors);try{return JSON.parse(readFileSync(file)).apiKeySource==='oauth';}catch{return false;}});
  const h=JSON.parse(readFileSync(file));
  await wait(()=>JSON.parse(readFileSync(file)).rateLimits?.five_hour.used_percentage===7);
  const limits=JSON.parse(readFileSync(file)).rateLimits;
  assert.equal(limits.seven_day.used_percentage,88);
  assert.ok(Date.now()-limits.at<5000);
  assert.equal(h.session,'lab-session');
  assert.equal((await fetch(`http://127.0.0.1:${h.port}/health`)).status,200);
  const ws=new WebSocket(`ws://127.0.0.1:${h.port}/ws?token=${h.token}`);
  const frames=[];ws.on('message',m=>frames.push(JSON.parse(m)));
  await new Promise((r,j)=>{ws.once('open',r);ws.once('error',j);});
  ws.send(JSON.stringify({t:'prompt',text:'unit-context'}));
  await wait(()=>JSON.parse(readFileSync(file)).context?.used===321);
  await wait(()=>JSON.parse(readFileSync(file)).rateLimits.at>limits.at);
  assert.deepEqual(JSON.parse(readFileSync(file)).context,{used:321,cap:400000});
  assert.ok(frames.some(e=>e.t==='hello'&&e.log.some(i=>i.t==='init'&&i.apiKeySource==='oauth')));
  ws.close();
  child.kill('SIGTERM');await new Promise(r=>child.once('exit',r));child=undefined;
  assert.ok(existsSync(file),'service metadata must survive clean stop for recovery');
  rmSync(file);
  const home=path.join(scratch,'home');
  mkdirSync(path.join(home,'.claude/projects/test'),{recursive:true});
  writeFileSync(path.join(home,'.claude/projects/test/lab-session.jsonl'),'runner history');
  child=spawn(process.execPath,['--experimental-strip-types','--no-warnings',path.resolve('services/host/src/service-runner.ts'),'--name','LAB','--resume','lab-session'],{cwd:scratch,env:{...env,HOME:home,AB_HOST_SDK:path.resolve('services/host/test/fake-sdk.mjs')},stdio:['ignore','ignore','pipe']});
  errors='';child.stderr.on('data',d=>errors+=d);
  await wait(()=>{if(child.exitCode!==null)throw Error(errors);try{return JSON.parse(readFileSync(file)).apiKeySource==='oauth';}catch{return false;}});
  const firstPid=JSON.parse(readFileSync(file)).pid;
  process.kill(firstPid,'SIGKILL');
  await wait(()=>{const h=JSON.parse(readFileSync(file));return h.pid!==firstPid&&h.apiKeySource==='oauth';});
  assert.equal(JSON.parse(readFileSync(file)).session,'lab-session');
  const nextPid=JSON.parse(readFileSync(file)).pid;
  writeFileSync(seat,JSON.stringify({name:'LAB',session:'lab-session',login_launcher:'claude-siso-3'}));
  await wait(()=>{if(child.exitCode!==null)throw Error(errors);const h=JSON.parse(readFileSync(file));return h.pid!==nextPid&&h.apiKeySource==='oauth';});
  assert.equal(JSON.parse(readFileSync(file)).configDir,path.join(home,'.config/claude-siso-3'));
  assert.equal(readFileSync(path.join(home,'.config/claude-siso-3/projects/test/lab-session.jsonl'),'utf8'),'runner history');
  assert.equal(existsSync(path.join(home,'.claude/projects/test/lab-session.jsonl')),false);
  child.kill('SIGTERM');await new Promise(r=>child.once('exit',r));child=undefined;
  console.log(JSON.stringify({check:'service unit: migration, malformed seat, billing label, plist, fake launchctl, fake SDK host and context',ok:true}));
} finally {if(child){child.kill('SIGTERM');await new Promise(r=>child.once('exit',r));}rmSync(scratch,{recursive:true,force:true});}
