/** Owner-side evidence store for the saved/fresh dashboard experiment (t-0391).
 * Only supervised host code should call the recording methods. The HTTP surface is read-only.
 */
import {createHash} from 'node:crypto';
import {execFile} from 'node:child_process';
import {mkdir,open,readFile,lstat,realpath} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {promisify} from 'node:util';
import type {WriterJobMeasurement} from './writer-gates.ts';

const exec=promisify(execFile), HASH=/^[a-f0-9]{64}$/, REV=/^[a-f0-9]{40,64}$/;
const ID=/^[A-Za-z0-9_-]{1,128}$/;
const safePath=(v:unknown):v is string=>typeof v==='string'&&v.length<=500&&!v.includes('\\')&&v.split('/').every(s=>!!s&&s!=='.'&&s!=='..'&&/^[\w .()-]+$/.test(s)&&!/^(?:\.env(?:\.|$)|\.credentials$|personal$)/.test(s));
const sha=(b:Buffer|string)=>createHash('sha256').update(b).digest('hex');
const jsonDigest=(v:unknown)=>sha(JSON.stringify(v));
export type RunStart={runId:string;mode:'saved'|'fresh';sessionId:string;resumedFrom:string|null;taskId:string;jobDigest:string;baseRevision:string;dossierDigest:string;sourceRevision:string;sourcePath:string;sourceFiles:{path:string;sha256:string}[]};
type Event={kind:'command'|'edit';at:number;command?:string;path?:string};
type Check={sourceRevision:string;command:string;exitCode:number};
type Shot={sourceRevision:string;sha256:string;viewport:{width:number;height:number};path:string};
type Stored={version:1;identity:RunStart;events:Event[];checks:Check[];shots:Shot[];evidenceBound:boolean;invalidReason:string|null;finalized:boolean;measurement:WriterJobMeasurement|null;measurementDigest:string|null};
const defaultDir=()=>process.env.AB_WRITER_MEASUREMENTS??path.join(os.homedir(),'.local/state/agent-base/writer-measurements');
function validStart(s:RunStart){if(!ID.test(s.runId)||!['saved','fresh'].includes(s.mode)||!s.sessionId||s.sessionId.length>256||!s.taskId||s.taskId.length>256||!HASH.test(s.jobDigest)||!HASH.test(s.dossierDigest)||!REV.test(s.baseRevision)||!REV.test(s.sourceRevision)||!(s.resumedFrom===null||ID.test(s.resumedFrom))||!path.isAbsolute(s.sourcePath)||!Array.isArray(s.sourceFiles)||!s.sourceFiles.length||s.sourceFiles.length>80||s.sourceFiles.some(f=>!safePath(f.path)||!HASH.test(f.sha256))||new Set(s.sourceFiles.map(f=>f.path)).size!==s.sourceFiles.length)throw Error('Invalid supervised writer run identity');}
async function verifySource(repo:string,revision:string,files:{path:string;sha256:string}[],compareDeclared=false){if((await exec('git',['-C',repo,'rev-parse','HEAD'])).stdout.trim()!==revision)throw Error('Writer source revision changed');for(const f of files){const b=await sourceBytes(repo,f.path);const actual=sha(b),committed=await exec('git',['-C',repo,'show',`${revision}:${f.path}`],{encoding:'buffer',maxBuffer:1024*1024});if(actual!==sha(committed.stdout)||(compareDeclared&&actual!==f.sha256))throw Error('Writer dossier inventory changed or is not committed');}}
async function sourceBytes(repo:string,relative:string){if(!safePath(relative))throw Error('Invalid writer inventory path');let current=repo;for(const part of relative.split('/')){current=path.join(current,part);if((await lstat(current)).isSymbolicLink())throw Error('Writer inventory cannot contain symbolic links');}const s=await lstat(current);if(!s.isFile()||s.size>1024*1024)throw Error('Writer inventory file unavailable or too large');return readFile(current);}
async function atomicWrite(file:string,value:unknown){await mkdir(path.dirname(file),{recursive:true,mode:0o700});const tmp=`${file}.${process.pid}.${Date.now()}.tmp`;const h=await open(tmp,'wx',0o600);try{await h.writeFile(JSON.stringify(value));await h.sync();}finally{await h.close();}await import('node:fs/promises').then(fs=>fs.rename(tmp,file));}
export function createWriterMeasurementOwner(dir=defaultDir()){
 if(!path.isAbsolute(dir))throw new Error('Writer measurement store path must be absolute');
 const fileFor=(id:string)=>{if(!ID.test(id))throw Error('Invalid measurement ID');return path.join(dir,`${id}.json`)};
 async function privateRoot(create:boolean){if(create)await mkdir(dir,{recursive:true,mode:0o700});const st=await lstat(dir);if(st.isSymbolicLink()||!st.isDirectory()||st.uid!==process.getuid?.()||st.mode&0o077||await realpath(dir)!==path.resolve(dir))throw Error('Writer measurement store is not private');}
 async function load(id:string):Promise<Stored>{await privateRoot(false);const f=fileFor(id),st=await lstat(f);if(st.isSymbolicLink()||!st.isFile()||st.uid!==process.getuid?.()||st.mode&0o077||st.size>512*1024)throw Error('Measurement record unavailable');const r=JSON.parse(await readFile(f,'utf8'));if(r?.version!==1||r.identity?.runId!==id||!Array.isArray(r.events)||!Array.isArray(r.checks)||!Array.isArray(r.shots))throw Error('Measurement record invalid');return r;}
 async function save(r:Stored){await privateRoot(true);await atomicWrite(fileFor(r.identity.runId),r);}
 return {
  /** Called by the supervised launcher after it has observed the actual provider session identity. */
  async begin(s:RunStart){validStart(s);const repo=await realpath(s.sourcePath);await verifySource(repo,s.sourceRevision,s.sourceFiles,true);const r:Stored={version:1,identity:{...s,sourcePath:repo},events:[],checks:[],shots:[],evidenceBound:false,invalidReason:null,finalized:false,measurement:null,measurementDigest:null};await save(r);return r;},
  async invalidate(id:string,reason:string){const r=await load(id);if(!r.invalidReason)r.invalidReason=String(reason||'Observer evidence invalid').slice(0,300);await save(r);},
  /** Host command observer: invoke only after a native command was actually dispatched. */
  async nativeCommand(id:string,command:string){if(!command||command.length>8000||/[\r\n]/.test(command))throw Error('Invalid native command event');const r=await load(id);if(r.finalized)throw Error('Measurement already finalized');r.events.push({kind:'command',at:Date.now(),command});await save(r);},
  /** Host filesystem observer: invoke on the first confirmed edit event, with the changed file path. */
  async nativeEdit(id:string,relativePath:string){if(!relativePath||path.isAbsolute(relativePath)||relativePath.split(/[\\/]/).includes('..'))throw Error('Invalid edit event');const r=await load(id);if(r.finalized)throw Error('Measurement already finalized');r.events.push({kind:'edit',at:Date.now(),path:relativePath});await save(r);},
  /** Bind executed evidence to the finished, committed result after the observer saw a real edit. */
  async bindEvidenceRevision(id:string){const r=await load(id);if(r.finalized||r.evidenceBound||!r.events.some(e=>e.kind==='edit'))throw Error('Writer result is not ready to bind');const repo=r.identity.sourcePath;const revision=(await exec('git',['-C',repo,'rev-parse','HEAD'])).stdout.trim();if(!REV.test(revision))throw Error('Writer result revision is unavailable');const files=[];for(const f of r.identity.sourceFiles){const b=await sourceBytes(repo,f.path);files.push({path:f.path,sha256:sha(b)});}await verifySource(repo,revision,files,true);r.identity.sourceRevision=revision;r.identity.sourceFiles=files;r.evidenceBound=true;await save(r);return revision;},
  /** Executes the declared check itself and records its real process exit code. */
  async executeCheck(id:string,command:string,args:string[]=[]){const r=await load(id);if(r.finalized||!r.evidenceBound)throw Error('Writer result revision is not bound');if(!command||command.length>8000||args.length>64||args.some(a=>typeof a!=='string'||a.length>4096))throw Error('Invalid check command');await verifySource(r.identity.sourcePath,r.identity.sourceRevision,r.identity.sourceFiles,true);let exitCode=0;try{await exec(command,args,{cwd:r.identity.sourcePath,timeout:15*60_000,maxBuffer:4*1024*1024});}catch(e:any){exitCode=Number.isInteger(e?.code)?e.code:1;}await verifySource(r.identity.sourcePath,r.identity.sourceRevision,r.identity.sourceFiles,true);r.checks.push({sourceRevision:r.identity.sourceRevision,command:[command,...args].join(' '),exitCode});await save(r);return exitCode;},
  /** Record a captured artifact; the producer hashes bytes from a non-symlink regular file. */
  async screenshot(id:string,artifact:string,viewport:{width:number;height:number}){if(!path.isAbsolute(artifact)||!Number.isSafeInteger(viewport?.width)||!Number.isSafeInteger(viewport?.height)||viewport.width<=0||viewport.height<=0||viewport.width>10000||viewport.height>10000)throw Error('Invalid screenshot evidence');const r=await load(id);if(r.finalized||!r.evidenceBound)throw Error('Writer result revision is not bound');const p=await realpath(artifact),st=await lstat(artifact);if(st.isSymbolicLink()||!st.isFile()||st.size<16||st.size>20*1024*1024)throw Error('Screenshot file unavailable or out of bounds');const b=await readFile(p);if(b.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')throw Error('Screenshot must be PNG');const width=b.readUInt32BE(16),height=b.readUInt32BE(20);if(width!==viewport.width||height!==viewport.height)throw Error('Screenshot viewport does not match artifact dimensions');r.shots.push({sourceRevision:r.identity.sourceRevision,sha256:sha(b),viewport:{...viewport},path:p});await save(r);},
  /** Finalize only when native events and all evidence are present. */
  async finalize(id:string){const r=await load(id);if(r.finalized)throw Error('Measurement already finalized');if(r.invalidReason)throw Error(`Writer measurement invalid: ${r.invalidReason}`);const edits=r.events.filter(e=>e.kind==='edit');const commands=r.events.filter(e=>e.kind==='command');if(!edits.length||!commands.length||!r.checks.length||!r.shots.length)throw Error('Native edit, command, check and screenshot evidence are all required');const firstEditIndex=r.events.findIndex(e=>e.kind==='edit');const first=r.events.slice(0,firstEditIndex).filter(e=>e.kind==='command').length;const m:WriterJobMeasurement={runId:id,mode:r.identity.mode,sessionId:r.identity.sessionId,resumedFrom:r.identity.resumedFrom,taskId:r.identity.taskId,jobDigest:r.identity.jobDigest,baseRevision:r.identity.baseRevision,dossierDigest:r.identity.dossierDigest,sourceRevision:r.identity.sourceRevision,commandsBeforeFirstEdit:first,totalCommands:commands.length,checks:r.checks,shots:r.shots.map(({path:_p,...s})=>s),measurementDigest:''};m.measurementDigest=jsonDigest(m);r.measurement=m;r.measurementDigest=m.measurementDigest;r.finalized=true;await save(r);return m;},
  /** Trusted resolver used by the comparison route; every evidence file is rechecked at read time. */
  async resolve(id:string):Promise<WriterJobMeasurement|null>{try{const r=await load(id),m=r.measurement;if(!r.finalized||r.invalidReason||!r.evidenceBound||!m||m.runId!==id||!r.measurementDigest)return null;const expected={...m,measurementDigest:''};if(jsonDigest(expected)!==r.measurementDigest||m.measurementDigest!==r.measurementDigest)return null;const repo=await realpath(r.identity.sourcePath);await verifySource(repo,m.sourceRevision,r.identity.sourceFiles,true);for(let i=0;i<r.shots.length;i++){const s=r.shots[i],st=await lstat(s.path);if(st.isSymbolicLink()||!st.isFile()||sha(await readFile(s.path))!==s.sha256)return null;}if(r.checks.some(c=>c.sourceRevision!==m.sourceRevision)||r.shots.some(s=>s.sourceRevision!==m.sourceRevision))return null;return m;}catch{return null;}},
 };
}
