import {createRequire} from 'node:module';
import {readFileSync,readdirSync,writeFileSync} from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'../..');
const webRequire=createRequire(path.join(root,'apps/web/package.json'));
const ts=webRequire('typescript');
const source=path.join(import.meta.dirname,'src');
const files=readdirSync(source).filter(name=>/\.tsx?$/.test(name)).map(name=>path.join(source,name));
const forbidden=/\b(fetch|WebSocket|localStorage|sessionStorage|CustomEvent)\s*\(|\b(localStorage|sessionStorage)\.|(?:from\s*|import\s*)["'][^"']*(?:apps\/|services\/)|\/api\//;
for(const file of files)assert.ok(!forbidden.test(readFileSync(file,'utf8')),`application data ownership leaked into ${path.basename(file)}`);
const nodeRequire=createRequire(path.join(root,'services/node/package.json'));
const nodeTypes=path.dirname(nodeRequire.resolve('@types/node/package.json'));
const react=path.dirname(webRequire.resolve('@types/react/package.json'));
const reactDom=path.dirname(webRequire.resolve('@types/react-dom/package.json'));
const viteClient=path.join(path.dirname(webRequire.resolve('vite/package.json')),'client.d.ts');
const options={target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,moduleResolution:ts.ModuleResolutionKind.Bundler,jsx:ts.JsxEmit.ReactJSX,strict:true,noUnusedLocals:true,noUnusedParameters:true,skipLibCheck:true,noEmit:true,allowImportingTsExtensions:true,types:['node'],typeRoots:[path.dirname(nodeTypes)],lib:['lib.es2022.d.ts','lib.dom.d.ts','lib.dom.iterable.d.ts'],paths:{'react':[path.join(react,'index.d.ts')],'react/*':[path.join(react,'*')],'react-dom':[path.join(reactDom,'index.d.ts')],'react-dom/*':[path.join(reactDom,'*')]}};
const adapters=['Composer.tsx','Hud.tsx','ContextMeter.tsx','ModelMenu.tsx','SubagentsPopover.tsx','ArtifactShelf.tsx'].map(name=>path.join(root,'apps/web/src/components',name));
const program=ts.createProgram([...files,...adapters,viteClient],options);
const diagnostics=ts.getPreEmitDiagnostics(program);
const owned=diagnostics.filter(d=>!d.file||files.includes(d.file.fileName)||adapters.includes(d.file.fileName));
const format=d=>`${d.file?path.relative(root,d.file.fileName):'compiler'}: ${ts.flattenDiagnosticMessageText(d.messageText,' ')}`;
const result={boundary:'passed',packageFiles:files.length,typecheck:owned.length?'failed':'passed',ownedDiagnostics:owned.map(format),dependencyDiagnostics:diagnostics.filter(d=>!owned.includes(d)).map(format)};
writeFileSync(path.join(root,'.agents/scratchpads/landing-20261006/composer-package-types.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(owned.length)process.exitCode=1;
