import { useState } from 'react';
import { HaloRim } from '../../../../packages/siso-shell/src/halo-rim/HaloRim';
import { LivingIcon } from '../../../../packages/halo-face/LivingIcon';
import { WorkspaceMark } from '../../../../packages/halo-face/WorkspaceMark';
import { AgentFace } from '../../../../packages/halo-face/AgentFace';
import { ChatRim } from './Composer';
import { ComposerFrame } from '../../../../packages/siso-composer/src/ComposerFrame';
import { ComposerHud } from '../../../../packages/siso-composer/src/ComposerHud';
import { ContextMeter } from '../../../../packages/siso-composer/src/ContextMeter';
import '../../../../packages/siso-tokens/siso.css';
import './ProductMapManual.css';

export function ProductMapManual({ section = 'states', evidenceBase = '/api/product-map/files' }: { section?: 'states' | 'animations' | 'edge-cases'; evidenceBase?: string }) {
  const [state,setState] = useState<'idle' | 'working' | 'voice'>('idle'), [paused,setPaused] = useState(false), [replay,setReplay] = useState(0), [receipt,setReceipt] = useState(0), [text,setText] = useState('');
  return <section className="pm-manual" aria-label="Component manual">
    <header><span>COMPONENT MANUAL · CURRENT SOURCE</span><h2>{section === 'states' ? 'States you can try' : section === 'animations' ? 'Motion with a purpose' : 'When the data is incomplete'}</h2><p>Real composer package, HaloRim, ChatRim and approved living components. These examples use local state and never send a message.</p></header>
    {section === 'states' && <>
      <div className="pm-manual-controls" aria-label="Composer state">{(['idle','working','voice'] as const).map(s=><button key={s} aria-pressed={state===s} onClick={()=>setState(s)}>{s}</button>)}</div>
      <div className="pm-manual-example"><ComposerFrame surface={HaloRim} state={state} hue="#8baeff" hud={<ComposerHud context={<ContextMeter value={35}/>} metrics={<span>Example reading · not live usage</span>}/>}><div className="pm-manual-input"><textarea aria-label="Manual composer draft" placeholder="Type a local example draft…" value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>setText('')}>Clear example</button></div><p>{state === 'working' ? 'Working · synthetic state' : state === 'voice' ? 'Voice rim only · microphone is off' : 'Idle · no agent connected'}</p></ComposerFrame></div>
      <code>{'<ComposerFrame surface={HaloRim} state="idle | working | voice" hud={…}>…</ComposerFrame>'}</code>
      <div className="pm-manual-examples">{(['waiting','working','needs-shaan','done'] as const).map(status=><figure key={status}><AgentFace name="Manual example" status={status} size={58} paused={paused}/><figcaption>{status}</figcaption></figure>)}</div>
      <h3>Composer state contract</h3><table><tbody><tr><th>Typing</th><td>Input focus and draft content belong to the caller. HaloRim supplies the material; it has no “typing” prop.</td></tr><tr><th>Working / idle</th><td>ChatRim accepts <code>working: boolean</code>, <code>accent?: string</code> (RGB channels), <code>hud?: ReactNode</code>, and children. HaloRim is the reusable shell.</td></tr><tr><th>Voice</th><td>HaloRim has a voice state; a nested <code>data-phase="listening"</code> mic also activates it. This example does not request microphone access.</td></tr><tr><th>Needs you / finished</th><td>AgentFace receives actual status. The app's worker popup owns completion and question events; the rim has no invented status variants.</td></tr><tr><th>Writing / narrow</th><td>ChatView owns writing mode and responsive composition. Resize this page to inspect the rim's available width; this is not full ChatView acceptance.</td></tr></tbody></table>
    </>}
    {section === 'animations' && <>
      <div className="pm-manual-controls"><button aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?'Resume living assets':'Pause living assets'}</button><button onClick={()=>setReplay(n=>n+1)}>Replay gesture</button></div>
      <div className="pm-manual-examples"><figure><LivingIcon name="library" size={72} paused={paused} replay={replay} interactive/><figcaption>Library · hover, focus or replay</figcaption></figure>{(['agent-base','siso-agency','halo'] as const).map(brand=><figure key={brand}><WorkspaceMark brand={brand} size={72} paused={paused} replay={replay} interactive/><figcaption>{brand} · Prism</figcaption></figure>)}</div>
      <div className="pm-manual-example"><ChatRim working={false} accent="139 174 255" acceptedReceipt={receipt ? { key:`manual-${receipt}`, text:'Synthetic acknowledgement example' } : null} hud={<p>Local example · no agent connection</p>}><div className="pm-manual-input"><span>Only a matching server acknowledgement triggers this receipt in the app.</span><button onClick={()=>setReceipt(n=>n+1)}>Simulate receipt</button></div></ChatRim></div>
      <table><tbody><tr><th>HaloRim</th><td>Working ring: 6 seconds. Voice ring: 3 seconds. The reduced motion media query removes rotation.</td></tr><tr><th>Acceptance receipt</th><td>ChatRim shows a new receipt key for 2.4 seconds; arrival is 240ms. Mount snapshots do not replay it. Hiding the document clears it.</td></tr><tr><th>Living icons</th><td><code>active</code>, <code>interactive</code> and <code>replay</code> request gestures. <code>paused</code>, reduced motion, document visibility and intersection gate motion; demo mode is reserved for comparisons.</td></tr><tr><th>Workspace marks</th><td>Keep the approved Prism geometry. <code>brand</code>, <code>size</code>, <code>paused</code>, <code>interactive</code> and <code>replay</code> are the integration points. Hidden or reduced-motion contexts stay still.</td></tr></tbody></table><p>Use your operating system's reduced-motion setting to inspect the actual media-query behavior. Pause above controls the living assets; the rim follows its own state and media query.</p>
    </>}
    {section === 'edge-cases' && <>
      <div className="pm-manual-example"><ChatRim working={false} hud={<ComposerHud context={<ContextMeter value={null}/>} metrics={<span>No HUD reported · values remain unknown</span>}/>}><div className="pm-manual-input"><textarea aria-label="Disconnected example" value="This example has no session." readOnly/><button disabled>No session</button></div></ChatRim></div>
      <table><tbody><tr><th>No HUD / stale limits</th><td>Keep absent values unknown. Do not turn missing usage into zero. A stale data timestamp must travel with the caller's HUD; ChatRim does not fetch or manufacture it.</td></tr><tr><th>No session</th><td>Disable transport controls in the caller. The composer shell is presentational and cannot establish a connection.</td></tr><tr><th>Worker still running</th><td>Opening its chat is separate from completion. Do not trigger the acceptance receipt or finish pop from a click.</td></tr><tr><th>Names collide</th><td>Use the server's agent/session identity for actions. A display name or face is not a routing key.</td></tr><tr><th>Terminal / SDK seat</th><td>Adapters determine supported send, interrupt and model capabilities. A common rim does not make their transports interchangeable.</td></tr><tr><th>390px</th><td>Keep controls reachable, wrap metadata, and avoid horizontal page overflow. Full chat overlays and the Agent Zero face require their own integrated layout check.</td></tr><tr><th>Failed rating save</th><td>The Product map keeps the note and current stored verdict until the server confirms the new record. Retrying is explicit.</td></tr></tbody></table>
    </>}
    <details className="pm-manual-api"><summary>Reusable composer API</summary><p>The current <code>@siso/composer</code> package takes observed data and callbacks. It has no Agent Base transport or live-account dependency.</p><table><tbody>
      <tr><th>ComposerFrame / ComposerHud</th><td>Pass <code>{'surface={HaloRim}'}</code>, state, hue, children, hud and acceptedReceipt. HUD slots: identity, context, usage, metrics, rate, activity; strip mode takes items and trailing.</td></tr>
      <tr><th>ContextMeter / ContextPopover</th><td><code>value: number | null</code>, optional label and compactAt; popover adds title, children and onOpenChange. Arc and number share one 650ms transition.</td></tr>
      <tr><th>UsagePopover / UsageRingCard</th><td>Windows have id, label, shortLabel, pct (number or null), and resetDescription. Pass freshness explicitly; the package does not infer account or reset time.</td></tr>
      <tr><th>ModelPicker</th><td>Supply the reported model, real model/effort options and selection callbacks. A request does not become an acknowledged selection until new props arrive.</td></tr>
      <tr><th>ActivityPill / ActivityPopover</th><td>Supply projected faces, counts, groups, items, progress and utility callbacks. The application owns session identity, actual running state and stop eligibility.</td></tr>
      <tr><th>ArtifactShelfView</th><td>Supply items with id, label and optional title/kind/icon, plus onOpen and onHide. The shelf owns presentation and more/less expansion.</td></tr>
    </tbody></table></details>
    <footer>Source owners: <code>packages/siso-composer/</code>, <code>packages/siso-shell/src/halo-rim/</code>, <code>packages/halo-face/</code>, <code>apps/web/src/components/Composer.tsx</code>. The input-bar README and REASONING log retain the decisions; this manual introduces no replacement design system. <a href={`${evidenceBase}/input-bar/README.md`}>Composer README</a> · <a href={`${evidenceBase}/input-bar/REASONING.md`}>Reasoning</a> · <a href={`${evidenceBase}/input-bar/FEEDBACK.md`}>Feedback</a></footer>
  </section>;
}
