import { useId, useState } from 'react'
import { AgentFace, LivingIcon, WorkspaceMark, type AgentFaceProps, type LivingIconName } from '../../../../packages/halo-face/living-assets'
import { useMotionGate, type MotionBankDemoProps } from './motion-bank-shared'
import './SessionReplay.css'

export type SessionReplayEventKind = 'assignment' | 'tool-working' | 'decision-waiting' | 'decision-accepted' | 'artifact-ready' | 'failed'
export type SessionReplayAgent = Pick<AgentFaceProps, 'name' | 'family' | 'project' | 'hue' | 'secondHue' | 'features'>
export type SessionReplayEvent = {
  readonly id: string
  /** Recorded display timestamp supplied by the owner; never generated by a clock. */
  readonly timestamp: string
  readonly kind: SessionReplayEventKind
  readonly title: string
  readonly receipt: string
  readonly reference?: string
  readonly owner: SessionReplayAgent
  readonly worker?: SessionReplayAgent
  readonly tool?: { readonly name: string; readonly detail: string }
  readonly decision?: { readonly question: string; readonly answer?: string }
  readonly output?: { readonly title: string; readonly detail: string; readonly icon?: LivingIconName }
}
export type SessionReplayProps = {
  events: readonly SessionReplayEvent[]
  cursor: number
  onSeek: (index: number) => void
  title?: string
  paused?: boolean
  className?: string
}

const labels: Record<SessionReplayEventKind, string> = {
  assignment: 'Assigned', 'tool-working': 'Tool working', 'decision-waiting': 'Decision waiting',
  'decision-accepted': 'Decision accepted', 'artifact-ready': 'Artifact ready', failed: 'Failed',
}
const clamp = (cursor: number, length: number) => Math.max(0, Math.min(length - 1, Number.isFinite(cursor) ? Math.trunc(cursor) : 0))

/** A read-only view of immutable observations. Seeking requests a cursor change only. */
export function SessionReplay({ events, cursor, onSeek, title = 'Recorded session', paused = false, className = '' }: SessionReplayProps) {
  const { ref, motion } = useMotionGate<HTMLElement>(paused)
  const uid = 'sr-' + useId().replace(/[^a-zA-Z0-9_-]/g, '')
  const index = clamp(cursor, events.length)
  const event = events[index]
  const failed = event?.kind === 'failed'
  const moving = motion && !failed
  const seek = (next: number) => { if (events.length) onSeek(clamp(next, events.length)) }
  const face = (agent: SessionReplayAgent, role: string) => <div className="sr-agent">
    <AgentFace {...agent} size={36} status={failed ? 'blocked' : 'waiting'} paused={!moving} track={false}/>
    <span><small>{role}</small><strong>{agent.name}</strong></span>
  </div>
  return <section ref={ref} className={'sr-root ' + className} data-motion={moving ? 'on' : 'off'} data-state={event?.kind ?? 'empty'} aria-labelledby={uid + '-title'}>
    <header className="sr-heading"><div className="sr-heading-copy"><WorkspaceMark brand="agent-base" size={32} paused={!moving}/><h3 id={uid + '-title'}>{title}</h3></div><span className="sr-replay">REPLAY</span></header>
    <div className="sr-position"><span>{events.length ? `${index + 1} of ${events.length} recorded events` : '0 recorded events'}</span><span>Cursor only · read-only</span></div>
    {event ? <div className="sr-frame" key={`${index}-${event.id}`}>
      <div className="sr-frame-top"><span className="sr-event-kind">{labels[event.kind]}</span><span className="sr-timestamp">{event.timestamp}</span></div>
      <div className="sr-path" aria-label="Recorded responsibility path">{face(event.owner, 'Owner')}{event.worker && <><span className="sr-path-arrow" aria-hidden="true">→</span>{face(event.worker, 'Worker')}</>}</div>
      <h4 className="sr-event-title">{event.title}</h4>
      {event.tool && <div className="sr-detail"><span className="sr-detail-label">Recorded tool</span><strong>{event.tool.name}</strong><p>{event.tool.detail}</p></div>}
      {event.decision && <div className="sr-detail"><span className="sr-detail-label">Recorded decision</span><strong>{event.decision.question}</strong><p>{event.decision.answer ?? 'No answer recorded at this position.'}</p></div>}
      {event.output && <div className="sr-output"><LivingIcon name={event.output.icon ?? 'web'} size={46} paused={!moving}/><div><span className="sr-detail-label">Recorded output</span><strong>{event.output.title}</strong><p>{event.output.detail}</p></div></div>}
      <div className="sr-receipt" role="status" aria-live="polite" aria-atomic="true"><span className="sr-detail-label">Receipt · {index + 1} of {events.length}</span><p>{event.receipt}</p>{event.reference && <code>{event.reference}</code>}</div>
    </div> : <div className="sr-empty"><strong>No recorded events</strong><p>Supply a recording to inspect its frames. No session state has changed.</p></div>}
    <div className="sr-scrubber"><label htmlFor={uid + '-seek'}>Replay position</label><input id={uid + '-seek'} type="range" min={0} max={Math.max(0, events.length - 1)} value={index} disabled={events.length < 2} onChange={e => seek(Number(e.target.value))} aria-valuetext={event ? `${index + 1} of ${events.length}: ${labels[event.kind]}, ${event.timestamp}` : 'No events'}/><div className="sr-range-labels"><span>{events[0]?.timestamp ?? 'Start'}</span><span>{events[events.length - 1]?.timestamp ?? 'End'}</span></div></div>
    <nav className="sr-controls" aria-label="Replay navigation"><button type="button" onClick={() => seek(0)} disabled={!events.length || index === 0}>Start</button><button type="button" onClick={() => seek(index - 1)} disabled={!events.length || index === 0}>Previous</button><button type="button" onClick={() => seek(index + 1)} disabled={!events.length || index === events.length - 1}>Next</button><button type="button" onClick={() => seek(events.length - 1)} disabled={!events.length || index === events.length - 1}>End</button></nav>
  </section>
}

const owner: SessionReplayAgent = { name: 'Agent Base', family: 'claude', project: 'Agent Base', features: { top: 6 } }
const worker: SessionReplayAgent = { name: 'Sol · Interface', family: 'codex', project: 'Agent Base', features: { top: 6 } }
const normalEvents: readonly SessionReplayEvent[] = [
  { id: 'assign', timestamp: '09:41:03', kind: 'assignment', owner, worker, title: 'A bounded task reaches the worker', receipt: 'Example assignment recorded: build the local review card.', reference: 'example/assignment/01' },
  { id: 'tool', timestamp: '09:42:18', kind: 'tool-working', owner, worker, title: 'Source inspection is in progress', tool: { name: 'Read component sources', detail: 'Recorded tool start; no completion result at this position.' }, receipt: 'Example tool invocation recorded. Outcome still pending.', reference: 'example/tool/02' },
  { id: 'waiting', timestamp: '09:44:06', kind: 'decision-waiting', owner, worker, title: 'The worker needs a direction', decision: { question: 'Use the compact card layout?' }, receipt: 'Example decision request recorded. No answer supplied yet.', reference: 'example/decision/03' },
  { id: 'accepted', timestamp: '09:45:27', kind: 'decision-accepted', owner, worker, title: 'The recorded answer is available', decision: { question: 'Use the compact card layout?', answer: 'Accepted: keep the compact layout.' }, receipt: 'Example answer recorded: compact layout accepted.', reference: 'example/decision/04' },
  { id: 'ready', timestamp: '09:48:12', kind: 'artifact-ready', owner, worker, title: 'A review object returns to its owner', output: { title: 'Local review card', detail: 'Recorded example artifact with a supplied verification receipt.', icon: 'web' }, receipt: 'Example artifact recorded as ready. Supplied check: 4 of 4 fixture assertions passed.', reference: 'example/artifact/05' },
]
const failedEvents: readonly SessionReplayEvent[] = [normalEvents[0], normalEvents[1], {
  id: 'failed', timestamp: '09:43:10', kind: 'failed', owner, worker, title: 'The recorded check failed', tool: { name: 'Check card layout', detail: 'Expected the title to fit at 320px; recorded fixture result: overflow.' }, receipt: 'Example failure recorded. No ready artifact or recovery result supplied.', reference: 'example/failure/03',
}]

export function SessionReplayDemo({ paused = false }: MotionBankDemoProps) {
  const [clip, setClip] = useState<'normal' | 'failure' | 'empty'>('normal')
  const [cursor, setCursor] = useState(0)
  const [receipt, setReceipt] = useState('Example recording selected at event 1.')
  const events = clip === 'normal' ? normalEvents : clip === 'failure' ? failedEvents : []
  const choose = (next: typeof clip) => { setClip(next); setCursor(0); setReceipt(`${next === 'empty' ? 'Empty' : next === 'normal' ? 'Normal' : 'Failure'} example selected; cursor reset to ${next === 'empty' ? 'empty' : 'event 1'}.`) }
  return <div className="sr-demo" data-demo-id="session-replay">
    <div className="sr-demo-tools"><span>Local synthetic example</span><div role="group" aria-label="Example recording"><button type="button" aria-pressed={clip === 'normal'} onClick={() => choose('normal')}>Normal sequence</button><button type="button" aria-pressed={clip === 'failure'} onClick={() => choose('failure')}>Failure sequence</button><button type="button" aria-pressed={clip === 'empty'} onClick={() => choose('empty')}>Empty recording</button></div></div>
    <SessionReplay events={events} cursor={cursor} onSeek={next => { setCursor(next); setReceipt(`Local onSeek received index ${next}; showing event ${next + 1} of ${events.length}.`) }} paused={paused} title="Interface session · example"/>
    <p className="sr-demo-receipt" role="status">{receipt}</p>
  </div>
}
