import { useState, type CSSProperties } from 'react'
import { createRoot } from 'react-dom/client'
import { AgentFace, WorkspaceMark, LivingIcon, LIVING_ICONS, INDUSTRY_ICON_NAMES, NAVIGATION_ICON_NAMES, type LivingIconName, type WorkspaceBrand } from '../../../packages/halo-face/living-assets'
import { MotionWorkbench } from './motion-workbench'
import './living-atlas.css'

declare global { interface Window { LIVING_KIT_URL?: string } }
const prior='http://127.0.0.1:8891/card/agent-faces-crown-logos-20261006/html'
const brands: {id:WorkspaceBrand;name:string;note:string;finish:string}[]=[
  {id:'agent-base',name:'Agent Base',note:'The approved blue lion',finish:'Cobalt / ice'},
  {id:'siso-agency',name:'SISO Agency',note:'The approved copper lion',finish:'Copper / flame'},
  {id:'halo',name:'HALO',note:'The approved pearl mark',finish:'Pearl / violet'},
]
function IconCard({name,paused,demo,replay,index}:{name:LivingIconName;paused:boolean;demo:boolean;replay:number;index:number}){
  const d=LIVING_ICONS[name]
  return <article className="la-icon-card" data-icon-card={name} style={{'--card-a':d.colorA} as CSSProperties}>
    <header><span>{String(index+1).padStart(2,'0')}</span><span className="la-colour-dot"/><code>{name}</code></header>
    <div className="la-icon-pair"><div><LivingIcon name={name} size={144} paused/><span>At rest</span></div><div><LivingIcon name={name} size={144} paused={paused} demo={demo} replay={replay} interactive/><span>{demo?'Gesture preview':'Hover · click · focus'}</span></div></div>
    <h3>{name==='ofm'?'OFM · Creator management':d.label}</h3><p>{d.motion}</p>
    <footer><div className="la-icon-sizes">{[24,32,48].map(size=><div key={size}><LivingIcon name={name} size={size} variant="glyph" paused/><span>{size}</span></div>)}</div><span className="la-size-note">px / glyph</span></footer>
  </article>
}
function App(){
  const [paused,setPaused]=useState(false),[demo,setDemo]=useState(false),[replay,setReplay]=useState(0)
  const [nav,setNav]=useState<LivingIconName>('library'),[hovered,setHovered]=useState<LivingIconName|null>(null)
  const [projectReplay,setProjectReplay]=useState(0),[agentReplay,setAgentReplay]=useState(0)
  const selected=LIVING_ICONS[nav]
  return <>
    <div className="la-top"><a href="#top" className="la-wordmark"><span className="la-monogram">S</span> SISO <span>/</span> Living atelier</a><nav aria-label="Gallery sections"><a href="#brands">Marks</a><a href="#industries">Industries</a><a href="#navigation">Sidebar</a><a href="#motion-lab">App motion</a><a href="#reuse">The kit ↗</a></nav><button className="la-pause" type="button" aria-pressed={paused} onClick={()=>setPaused(v=>!v)}>{paused?'▶ Resume motion':'Ⅱ Pause motion'}</button></div>
    <main className="la" id="top">
      <section className="la-hero"><div className="la-hero-copy"><span className="la-eyebrow">AGENT BASE · COLLECTION 03</span><h1>A little character.<br/><em>Everywhere it belongs.</em></h1><p>The marks you loved, kept intact. A new family for the worlds around them—crafted in glass, metal, light, and a little restraint.</p><div className="la-hero-actions"><a href="#industries">Explore the family <span>↓</span></a><a href="#motion-lab">Try the app details ↗</a></div><div className="la-counts"><span><b>03</b> approved marks</span><span><b>15</b> new symbols</span><span><b>05</b> app interactions</span></div></div>
      <div className="la-hero-stage" aria-label="The living identity collection"><div className="la-orbit la-orbit-a"/><div className="la-orbit la-orbit-b"/><div className="la-stage-lion"><WorkspaceMark brand="siso-agency" size={144} paused={paused} interactive replay={replay}/></div><div className="la-stage-beacon"><LivingIcon name="agent-base" size={184} paused={paused} interactive demo={demo} replay={replay}/></div><div className="la-stage-halo"><WorkspaceMark brand="halo" look="relief" size={114} paused={paused} interactive replay={replay}/></div><div className="la-stage-face"><AgentFace name="Codex Royal" family="codex" features={{head:4,eyes:0,sides:1,top:6}} hue={265} secondHue={44} status="waiting" size={100} paused={paused} track interactive/></div><span className="la-stage-caption">A shared material. An individual character.</span></div></section>
      <div className="la-controls"><div><span className="la-live-dot"/><b>Icons rest until you interact.</b><span> Hover or focus an icon. Click to replay.</span></div><div><button type="button" aria-pressed={demo} onClick={()=>setDemo(v=>!v)}>{demo?'Stop hover previews':'Preview hover loops'}</button><button type="button" onClick={()=>setReplay(v=>v+1)}>Replay visible icons ↻</button></div></div>

      <section id="brands" className="la-section"><header className="la-section-head"><div><span className="la-eyebrow">01 / THE APPROVED CORE</span><h2>Keep the royalty.</h2></div><p>These stay in the kit exactly as approved. The crown, sixteen face finishes, and original comparisons remain in the earlier atelier.</p></header><div className="la-brand-grid">{brands.map(b=><article className="la-brand-card" key={b.id}><div><span className="la-kicker">{b.finish}</span><span className="la-kept">Preserved</span></div><WorkspaceMark brand={b.id} size={144} interactive paused={paused} replay={replay}/><h3>{b.name}</h3><p>{b.note}</p><div className="la-brand-sizes">{[24,32,48].map(size=><WorkspaceMark key={size} brand={b.id} size={size} paused={paused} replay={replay}/>)}<a href={prior+'#logos'}>All three treatments ↗</a></div></article>)}</div>
      <div className="la-beacon-study"><div className="la-beacon-copy"><span className="la-eyebrow">NEW DIRECTION / AGENT BASE</span><h3>The Beacon.</h3><p>A home for intelligence. Three structural edges hold a bright central core. It gives Agent Base its own silhouette while SISO Agency keeps the lion.</p><p className="la-note">A proposed alternative, presented beside the approved mark.</p><button type="button" onClick={()=>setAgentReplay(v=>v+1)}>Light the core ↗</button></div><div className="la-beacon-pair"><div><WorkspaceMark brand="agent-base" size={144} paused/><span>Approved lion</span></div><span className="la-and">+</span><div><LivingIcon name="agent-base" size={144} interactive demo={demo} paused={paused} replay={agentReplay+replay}/><span>Beacon candidate</span></div></div></div></section>

      <section id="industries" className="la-section"><header className="la-section-head"><div><span className="la-eyebrow">02 / INDUSTRY IDENTITIES</span><h2>Six worlds. One family.</h2></div><p>Recognisable at sidebar size. Rich enough for an industry card. Each gesture belongs to the object.</p></header><div className="la-icon-grid">{INDUSTRY_ICON_NAMES.map((name,index)=><IconCard key={name} {...{name,index,paused,demo,replay}}/>)}</div></section>

      <section id="projects" className="la-section"><header className="la-section-head"><div><span className="la-eyebrow">03 / PROJECT IDENTITIES</span><h2>A place for each pursuit.</h2></div><p>Estate and LifeLog carry the same symbol from card to navigation. Maths Innovations gets a new infinity ribbon and a crystalline centre.</p></header><div className="la-project-grid">{[{name:'estate',kind:'SYSTEMS & OWNERSHIP',title:'SISO Estate',copy:'The machines, assets, and systems that keep everything in order.'},{name:'lifelog',kind:'A PERSONAL CHRONICLE',title:'LifeLog',copy:'Moments and reflections, held in one continuous story.'},{name:'maths-innovations',kind:'DISCOVERY & PROOF',title:'Maths Innovations',copy:'An idea becomes a connection. A connection becomes a proof.'}].map(p=><article key={p.name} className="la-project-card" style={{'--card-a':LIVING_ICONS[p.name as LivingIconName].colorA} as CSSProperties}><span className="la-kicker">{p.kind}</span><LivingIcon name={p.name as LivingIconName} size={112} paused={paused} interactive demo={demo} replay={replay+projectReplay}/><h3>{p.title}</h3><p>{p.copy}</p><div><span>Project card concept</span><button type="button" onClick={()=>setProjectReplay(n=>n+1)} aria-label={'Replay '+p.title}>↗</button></div></article>)}</div><div className="la-project-scale"><span>Maths, at navigation size</span>{[24,32,48].map(size=><LivingIcon key={size} name="maths-innovations" variant="glyph" size={size} paused/>)}</div></section>

      <section id="navigation" className="la-section"><header className="la-section-head"><div><span className="la-eyebrow">04 / THE SIDEBAR</span><h2>Useful when small.<br/>Alive when invited.</h2></div><p>Try the sidebar first, then inspect the full set. Colour helps you recognise the destination; movement acknowledges your attention.</p></header><div className="la-nav-demo"><nav aria-label="Synthetic sidebar preview" className="la-demo-nav"><span className="la-kicker">YOUR WORKSPACE / PREVIEW</span>{NAVIGATION_ICON_NAMES.map(name=><button type="button" key={name} aria-pressed={nav===name} onClick={()=>setNav(name)} onPointerEnter={()=>setHovered(name)} onPointerLeave={()=>setHovered(null)} onFocus={()=>setHovered(name)} onBlur={()=>setHovered(null)}><LivingIcon name={name} size={32} variant="glyph" paused={paused} active={hovered===name}/><span>{name==='agent-base'?'Agent Base':LIVING_ICONS[name].label}</span><span aria-hidden="true">›</span></button>)}</nav><div className="la-nav-focus"><span className="la-kicker">SELECTED ICON</span><LivingIcon name={nav} size={176} paused={paused} interactive demo={demo} replay={replay}/><h3>{selected.label}</h3><p>{selected.description}</p><div><LivingIcon name={nav} variant="glyph" size={24} paused/><LivingIcon name={nav} variant="glyph" size={32} paused/><LivingIcon name={nav} variant="glyph" size={48} paused/><span>24 / 32 / 48 px</span></div></div></div><div className="la-icon-grid">{NAVIGATION_ICON_NAMES.map((name,index)=><IconCard key={name} {...{name,index,paused,demo,replay}}/>)}</div></section>

      <MotionWorkbench paused={paused}/>

      <section id="reuse" className="la-section la-reuse"><div><span className="la-eyebrow">06 / YOUR REUSABLE KIT</span><h2>Keep it. Use it everywhere.</h2><p>Three components, a shared visual language, and quiet defaults. The download includes the React source, thirty-three still SVGs, a catalogue, and usage notes.</p><div className="la-downloads">{window.LIVING_KIT_URL?<a download="siso-living-assets-20261006.zip" target="_blank" rel="noopener" href={window.LIVING_KIT_URL}>Download the kit <span>↓</span></a>:<span>The source kit is in packages/halo-face.</span>}<a href={prior+'#crowns'}>Faces, crowns & 16 finishes ↗</a></div><div className="la-kit-facts"><span>React + SVG</span><span>Native reduced motion</span><span>No icon frame loop</span><span>Local preview</span></div></div><div className="la-code"><div><span>Three ways to reuse</span><span>React</span></div><pre><code>{`import { AgentFace, WorkspaceMark, LivingIcon }\n  from './living-assets'\n\n<AgentFace\n  name="Astra" family="codex"\n  features={{ top: 6 }} size={32}\n/>\n\n<WorkspaceMark\n  brand="siso-agency" size={48}\n/>\n\n<LivingIcon\n  name="library" size={32}\n  variant="glyph" active={hovered}\n/>`}</code></pre></div></section>
      <footer className="la-footer"><span>SISO / Living atelier · 06 October 2026</span><span>Review branch + local preview · app integration pending</span><a href="#top">Back to the collection ↑</a></footer>
    </main>
  </>
}

createRoot(document.getElementById('root')!).render(<App/> )
