import {createRoot} from 'react-dom/client';
import {AgentFace} from '../../../packages/halo-face/AgentFace';
import {colourways,featureNames,type AgentStatus,type FaceFamily} from '../../../packages/halo-face/identity';
import '../src/index.css';
import './original-faces-review.css';
const selections=[{family:'claude',top:0,eyes:0,colour:0},{family:'codex',top:1,eyes:1,colour:1},{family:'claude',top:2,eyes:2,colour:2},{family:'codex',top:3,eyes:3,colour:6},{family:'claude',top:4,eyes:4,colour:9},{family:'codex',top:6,eyes:5,colour:12}] as const;
const states:[string,AgentStatus][]=[['Idle','waiting'],['Working','working'],['Needs you','needs-shaan']];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
createRoot(document.getElementById('root')!).render(<main className="face-review"><header><p>AGENT BASE · ORIGINAL FACE FAMILY</p><h1>One face family. Six existing combinations.</h1><p>The real AgentFace component, using the approved Prism direction. Synthetic identity and states. No recorded human rating.</p><strong>Motion preference: {reduced?'Reduced motion':'Normal motion'}</strong><nav aria-label="Face combinations">{selections.map((s,i)=><a key={i} href={'#choice-'+i}>{i+1}. {featureNames.top[s.top]}</a>)}</nav></header>{selections.map((s,i)=>{const colour=colourways[s.colour];return <section key={i} id={'choice-'+i} aria-labelledby={'title-'+i}><h2 id={'title-'+i}>{i+1}. {featureNames.top[s.top]} · {featureNames.eyes[s.eyes]} eyes · {colour.name}</h2><p>{s.family} geometry · existing accessories and palette · head shape unchanged for the family</p><div className="face-states">{states.map(([label,status])=><figure key={status}><div role="img" aria-label={`${featureNames.top[s.top]}, ${label}, ${s.family}`} data-face-state={status}><AgentFace name={'Synthetic '+s.family+' '+i} family={s.family as FaceFamily} direction="prism" size={118} status={status} hue={colour.hue} secondHue={colour.other} features={{head:s.family==='claude'?0:4,top:s.top,eyes:s.eyes,sides:i%6}}/></div><figcaption>{label}</figcaption></figure>)}</div></section>})}<footer>These renders demonstrate component appearance and motion preference handling. Installed identity selection and owner acceptance remain unverified.</footer></main>);
