// Fake-only ownership, transcription, history and rendered acceptance. Never touches a live agent or voice data.
import { spawn } from "node:child_process";
import { createServer } from "node:http";
import { createRequire } from "node:module";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, renameSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { tmpdir } from "node:os";
import net from "node:net";
const root = path.resolve(import.meta.dirname, "../../..");
const scratch = mkdtempSync(path.join(tmpdir(), ".siso-ephemeral-dictation."));
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const results = [];
const details = [];
const check = (name, ok) => { results.push(Boolean(ok)); details.push({name, ok: Boolean(ok)}); writeFileSync(path.join(shots, "dictation-checks.json"), JSON.stringify({ checks: results.length, passed: results.filter(Boolean).length, last: name, ok: Boolean(ok), results: details })); console.log(JSON.stringify({ check: name, ok: Boolean(ok) })); };
const freePort = async () => { const s = net.createServer(); await new Promise((r) => s.listen(0, "127.0.0.1", r)); const p = s.address().port; await new Promise((r) => s.close(r)); return p; };
const shots = path.join(root, ".shots"); mkdirSync(shots, { recursive: true });
const jobs = ["com.siso.voice.runtime", "com.siso.voice-sync", "com.siso.voice.extra"];
const agents = path.join(scratch, "LaunchAgents"); mkdirSync(agents);
for (const label of jobs) writeFileSync(path.join(agents, `${label}.plist`), `<?xml version="1.0"?><plist version="1.0"><dict><key>Label</key><string>${label}</string></dict></plist>`);
const store = path.join(scratch, "jobs.json"), callsFile = path.join(scratch, "calls.jsonl");
writeFileSync(store, JSON.stringify(jobs)); writeFileSync(callsFile, "");
const pidFile = path.join(scratch, "runtime-pid");
const script = path.join(scratch, "launchctl.mjs");
writeFileSync(script, `import {readFileSync,writeFileSync,appendFileSync,existsSync} from 'node:fs';
const [verb,domain,arg]=process.argv.slice(2);let jobs=JSON.parse(readFileSync(${JSON.stringify(store)},'utf8'));
appendFileSync(${JSON.stringify(callsFile)},JSON.stringify([verb,domain,arg])+'\\n');
const label=verb==='bootstrap'?arg.split('/').at(-1).replace('.plist',''):String(domain).split('/').at(-1);
if(verb==='list'){console.log(jobs.map(j=>'123 0 '+j).join('\\n'));process.exit(0)}
if(verb==='print'){if(!jobs.includes(label))process.exit(113); const pid=label==='com.siso.voice.runtime'&&existsSync(${JSON.stringify(pidFile)})?readFileSync(${JSON.stringify(pidFile)},'utf8'):'0'; console.log('state = running\\nproperties = keepalive\\npid = '+pid);process.exit(0)}
if(verb==='bootout'){if(!jobs.includes(label))process.exit(113); jobs=jobs.filter(j=>j!==label)}
if(verb==='bootstrap'){if(jobs.includes(label))process.exit(1);jobs.push(label)}
writeFileSync(${JSON.stringify(store)},JSON.stringify(jobs));`);
const ctl = path.join(scratch, "launchctl"); writeFileSync(ctl, `#!/bin/sh\nexec '${process.execPath}' '${script}' "$@"\n`); chmodSync(ctl, 0o755);
const settings = path.join(scratch, ".settings"); writeFileSync(settings, JSON.stringify({ groq_api_key: "fake-dictation-key" }), { mode: 0o600 });
const prefs = path.join(scratch, "voice.plist");
writeFileSync(prefs, `<?xml version="1.0"?><plist version="1.0"><dict><key>post_processing_enabled</key><true/><key>custom_system_prompt</key><string>Preserve intent and remove fillers.</string><key>custom_vocabulary</key><string>SISO</string></dict></plist>`);
let groqMode = "ok", cleanupMode = "ok", groqCalls = 0, cleanupCalls = 0;
const groq = createServer(async (req, res) => {
  const chunks=[];for await(const c of req) chunks.push(c);
  const body=Buffer.concat(chunks).toString();
  if(req.url==='/models')return res.writeHead(req.headers.authorization==='Bearer gsk_lab_good_key_0123456789abcdef'?200:401,{'content-type':'application/json'}).end('{}');
  if(req.url==='/cleanup'){cleanupCalls++;const messages=JSON.parse(body).messages;if(cleanupMode==='fail')return res.writeHead(500).end();
    return res.writeHead(200,{'content-type':'application/json'}).end(JSON.stringify({choices:[{message:{content: messages[0].content.includes('Preserve intent') ? 'A polished fake dictation for SISO.' : 'wrong prompt'}}]}));}
  groqCalls++;
  if(groqMode==='slow')await new Promise((r)=>setTimeout(r,1500));
  if(groqMode==='reject')return res.writeHead(400,{'content-type':'application/json'}).end(JSON.stringify({error:{message:'fixture malformed recording'}}));
  if(groqMode==='fail')return res.writeHead(401,{'content-type':'application/json'}).end(JSON.stringify({error:{message:'fixture refusal'}}));
  res.writeHead(200,{'content-type':'application/json'}).end(JSON.stringify({text:groqMode==='empty'?'':'um a fake dictation for SISO'}));
});
await new Promise((r)=>groq.listen(0,'127.0.0.1',r));
const base=`http://127.0.0.1:${await freePort()}`;
const env={...process.env,HOME:scratch,AB_PORT:base.split(':').at(-1),AB_HERDR:`${process.execPath} ${path.join(root,'services/node/test/fake-herdr.mjs')}`,FAKE_HERDR_AGENTS:'[]',AB_STATE:path.join(scratch,'rows.json'),AB_REGISTRY:path.join(scratch,'registry.json'),AB_CTX_DIR:path.join(scratch,'ctx'),AB_HOSTS_DIR:path.join(scratch,'hosts'),AB_RESURRECT_DIR:path.join(scratch,'none'),AB_CONSOLE_EVENTS:path.join(scratch,'none.jsonl'),AB_HUB_HOME:scratch,AB_VOICE_SETTINGS:settings,AB_VOICE_PREFS:prefs,AB_VOICE_DB:path.join(scratch,'absent.sqlite'),AB_DICTATION_DIR:path.join(scratch,'dictation'),AB_VOICE_WATCH:'1',AB_VOICE_WATCH_MS:'200',AB_VOICE_LAUNCH_AGENTS:agents,AB_LAUNCHCTL:ctl,AB_GROQ_URL:`http://127.0.0.1:${groq.address().port}/transcribe`,AB_GROQ_MODELS_URL:`http://127.0.0.1:${groq.address().port}/models`,AB_DICTATION_CLEANUP_URL:`http://127.0.0.1:${groq.address().port}/cleanup`,AB_DICTATION_ACK_MS:'1600',AB_DICTATION_RETRY_MS:'300',AB_DICTATION_SWEEP_MS:'500',AB_VOICE_OUTBOX:path.join(scratch,'outbox.ndjson')};
delete env.GROQ_API_KEY;
let node, browser, timer, stoppingFixture, nativeEnabled=true, nativeOn=false;
const replies=[];
async function api(route,body,headers={}){const r=await fetch(`${base}/api/dictation/${route}`,body===undefined?{headers}:{method:'POST',headers:{'content-type':Buffer.isBuffer(body)?'audio/mp4':'application/json',...headers},body:Buffer.isBuffer(body)?body:JSON.stringify(body)});const text=await r.text();replies.push(text);return {status:r.status,data:JSON.parse(text)};}
const calls=()=>readFileSync(callsFile,'utf8').trim().split('\n').filter(Boolean).map(JSON.parse);
try {
  node=spawn(process.execPath,['--experimental-strip-types','--no-warnings','src/server.ts'],{cwd:path.join(root,'services/node'),env,stdio:['ignore','ignore','pipe']});
  let stderr='';node.stderr.on('data',(c)=>stderr+=c);
  for(let i=0;i<80;i++){try{if((await api('status')).status===200)break;}catch{}await sleep(150);}
  const first=await api('status');check('default owner stays SISO Voice; no job unloaded',first.data.owner==='siso-voice'&&!calls().some(([v])=>v==='bootout'));
  check('foreign origin cannot switch ownership',(await api('owner',{owner:'agent-base'},{origin:'https://foreign.invalid'})).status===403);
  check('invalid ownership refused',(await api('owner',{owner:'broken'})).status===400);
  check('desktop must be present before takeover',(await api('owner',{owner:'agent-base'})).status===409);
  // Simulated native handshake, no event tap, keyboard, microphone, or real app involved.
  let nativeBusy=false;
  timer=setInterval(async()=>{if(nativeBusy)return;nativeBusy=true;try{const s=(await api('status')).data;{nativeOn=nativeEnabled&&s.owner==='agent-base';await api('native',{registered:nativeOn,permission:true});}}catch{}finally{nativeBusy=false}},90);
  await api('native',{registered:false,permission:true});
  check('takeover succeeds after native acknowledgment',(await api('owner',{owner:'agent-base'})).status===200);
  check('every hotkey-owning SISO Voice job unloaded; the JARVIS sync job left running',calls().filter(([v])=>v==='bootout').length===2&&!calls().some(([v,l])=>v==='bootout'&&String(l).endsWith('voice-sync')));
  const beforeKick=calls().filter(([v])=>v==='kickstart').length;await sleep(500);
  check('voice watcher never restarts the old owner while dictating',calls().filter(([v])=>v==='kickstart').length===beforeKick);
  const fixture=readFileSync(path.join(import.meta.dirname,'fixtures/voice/hello-a0.m4a'));
  const take=await api('transcribe?app=Fake%20Editor&bundleId=com.fake.editor',fixture);
  check('fake audio transcribes, cleanup runs, history captures app and time',take.status===200&&take.data.text==='A polished fake dictation for SISO.'&&take.data.app==='Fake Editor'&&Boolean(take.data.timestamp)&&cleanupCalls===1);
  const malformed=await api('transcribe',Buffer.from('junk'));
  check('malformed audio refused without a provider call',malformed.status===400&&groqCalls===1);
  groqMode='empty';check('empty speech is not pasted or saved',(await api('transcribe',fixture)).status===422);const silentWav=Buffer.alloc(44+64000);silentWav.write('RIFF',0);silentWav.writeUInt32LE(36+64000,4);silentWav.write('WAVE',8);silentWav.write('fmt ',12);silentWav.writeUInt32LE(16,16);silentWav.writeUInt16LE(1,20);silentWav.writeUInt16LE(1,22);silentWav.writeUInt32LE(16000,24);silentWav.writeUInt32LE(32000,28);silentWav.writeUInt16LE(2,32);silentWav.writeUInt16LE(16,34);silentWav.write('data',36);silentWav.writeUInt32LE(64000,40);
  groqMode='ok';const callsBefore=groqCalls;const hush=await api('transcribe',silentWav);check('silence is never sent to Groq, so it cannot come back as "Thank you"',hush.status===422&&groqCalls===callsBefore);
  groqMode='fail';const queued=await api('transcribe?app=Slow%20App&bundleId=com.slow.app',fixture);const pend=path.join(scratch,'dictation/pending');
  check('a Groq failure keeps the recording on disk and answers 202 queued',queued.status===202&&queued.data.queued===true&&existsSync(path.join(pend,`${queued.data.id}.wav`)));groqMode='ok';
  for(let i=0;i<40&&existsSync(path.join(pend,`${queued.data.id}.wav`));i++)await sleep(150);
  check('the saved recording is retried until it lands in history, then its file goes',!existsSync(path.join(pend,`${queued.data.id}.wav`))&&(await api('history?q=')).data.entries.some((e)=>e.id===queued.data.id&&e.app==='Slow App'));
  cleanupMode='fail';const fallback=await api('transcribe?app=Fake%20Editor&bundleId=com.fake.editor',fixture);check('cleanup failure keeps original transcript',fallback.status===200&&fallback.data.cleanup==='fallback');cleanupMode='ok';
  const h=await api('history?q=polished'),none=await api('history?q=%25');
  check('history search returns only matching dictations and escapes wildcard',h.data.entries.length===2&&none.data.entries.length===0);
  check('JARVIS outbox gets one text-only line per dictation, as SISO Voice wrote',readFileSync(path.join(scratch,'outbox.ndjson'),'utf8').trim().split('\n').map((l)=>JSON.parse(l)).every((l)=>l.intent==='dictation'&&l.raw_transcript&&l.client_id&&!('audio' in l))&&readFileSync(path.join(scratch,'outbox.ndjson'),'utf8').trim().split('\n').length===3);
  check('history store is private and contains only own dictations',h.data.total===3&&(statSync(path.join(scratch,'dictation/history.sqlite')).mode&0o777)===0o600);
  await api('events',{phase:'idle'});
  const require=createRequire(import.meta.url);const {webkit}=existsSync('/tmp/ab-hub3-tools/node_modules/playwright')?require('/tmp/ab-hub3-tools/node_modules/playwright'):await import('playwright');
  browser=await webkit.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:960}});const errors=[];page.on('pageerror',(e)=>errors.push(e.message));
  await page.goto(base);await page.locator('.siso-app__rail-btn[aria-label^="Voice"]').first().click();await page.locator('[data-testid=dictation-entry]').first().waitFor();
  check('rendered Voice home shows the latest dictations from Agent Base',await page.locator('[data-testid=dictation-entry]').filter({hasText:'Fake Editor'}).count()===2);
  await page.getByRole('navigation',{name:'Voice pages'}).getByRole('button',{name:/^History/}).click();await page.getByLabel('Search dictations').fill('polished');await page.waitForTimeout(500);check('rendered history holds Agent Base dictations and search filters them',await page.locator('[data-voice-row]').count()===2);
  await page.getByRole('navigation',{name:'Voice pages'}).getByRole('button',{name:'Home'}).click();await page.locator('[data-testid=dictation-entry]').first().waitFor();
  await page.evaluate(() => {
    window.__dictationCopies = [];
    window.__dictationPastes = [];
    Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async (text) => { window.__dictationCopies.push(text); } } });
    window.__TAURI_INTERNALS__ = { invoke: async (command, args) => { if (command === 'dictation_paste') window.__dictationPastes.push(args); return null; } };
  });
  await page.getByRole('button', { name: 'Copy what you said in Fake Editor' }).first().click();
  await page.getByRole('button', { name: 'Paste again into Fake Editor' }).first().click();
  check('copy and re-paste use transcript and original app', await page.evaluate(() => window.__dictationCopies.length === 1 && window.__dictationPastes.length === 1 && window.__dictationPastes[0].bundleId === 'com.fake.editor' && window.__dictationPastes[0].text === window.__dictationCopies[0]));
  await page.screenshot({path:path.join(shots,'dictation-1440.png')});
  await page.setViewportSize({width:390,height:844});await page.getByRole('button', {name:'Show or hide the side nav'}).click();await page.locator('[data-testid=voice-main]').waitFor({state:'visible'});await page.screenshot({path:path.join(shots,'dictation-390.png')});
  check('mobile transcript pane has no horizontal overflow',await page.locator('[data-testid=voice-main]').evaluate((e)=>e.clientWidth>200&&e.scrollWidth<=e.clientWidth+1));
  check('zero browser runtime errors',errors.length===0);
  await api('events',{phase:'recording'});
  const quietTake=await api('transcribe?app=Rolling%20Fixture&quiet=1',fixture);
  check('quiet part succeeds and gets its own History row without changing recording phase',quietTake.status===200&&(await api('status')).data.phase==='recording'&&(await api('history?q=')).data.entries.some((e)=>e.id===quietTake.data.id));
  const quietBad=await api('transcribe?quiet=1',Buffer.from('junk'));
  check('quiet part errors preserve recording phase and still return their own error',quietBad.status===400&&quietBad.data.error&&(await api('status')).data.phase==='recording');
  groqMode='fail';
  const quietQueued=await api('transcribe?quiet=1',fixture);
  check('quiet queued part preserves recording and retains its audio',quietQueued.status===202&&(await api('status')).data.phase==='recording'&&existsSync(path.join(pend,`${quietQueued.data.id}.wav`)));
  const retryWav=path.join(pend,`${quietQueued.data.id}.wav`),retryMeta=path.join(pend,`${quietQueued.data.id}.json`);
  const wavMtime=statSync(retryWav).mtimeMs;chmodSync(retryWav,0o400);
  for(let i=0;i<40&&JSON.parse(readFileSync(retryMeta,'utf8')).tries<3;i++)await sleep(150);
  check('retry never rewrites the existing private audio',JSON.parse(readFileSync(retryMeta,'utf8')).tries>=3&&statSync(retryWav).mtimeMs===wavMtime&&readFileSync(retryWav).equals(fixture));
  mkdirSync(`${retryMeta}.next`);const retryCalls=groqCalls;
  for(let i=0;i<40&&groqCalls===retryCalls;i++)await sleep(150);
  await sleep(100);
  check('failed metadata update leaves the queued audio intact',groqCalls>retryCalls&&statSync(retryWav).mtimeMs===wavMtime&&readFileSync(retryWav).equals(fixture));
  rmSync(`${retryMeta}.next`,{recursive:true});
  groqMode='reject';
  for(let i=0;i<50&&!existsSync(path.join(scratch,'dictation/unreadable',`${quietQueued.data.id}.wav`));i++)await sleep(150);
  check('permanently rejected retry keeps its original audio in unreadable',existsSync(path.join(scratch,'dictation/unreadable',`${quietQueued.data.id}.wav`))&&readFileSync(path.join(scratch,'dictation/unreadable',`${quietQueued.data.id}.wav`)).equals(fixture));
  // A file at the queue directory path deterministically simulates unavailable storage.
  renameSync(pend,`${pend}-fixture-held`); writeFileSync(pend,'fixture blocks queue directory');
  groqMode='fail'; const unsaved=await api('transcribe?quiet=1',fixture);
  check('unavailable queue storage never acknowledges 202 saved',unsaved.status===507&&unsaved.data.queued!==true&&(await api('status')).data.phase==='recording');
  rmSync(pend);renameSync(`${pend}-fixture-held`,pend);groqMode='ok';
  writeFileSync(settings,JSON.stringify({}));
  const missingKey=await api('transcribe?quiet=1',fixture);
  check('missing provider credentials retain audio for retry',missingKey.status===202&&existsSync(path.join(pend,`${missingKey.data.id}.wav`)));
  writeFileSync(settings,JSON.stringify({groq_api_key:'fake-dictation-key'}));
  for(let i=0;i<40&&existsSync(path.join(pend,`${missingKey.data.id}.wav`));i++)await sleep(150);
  check('restored fixture credentials recover the queued part into History',(await api('history?q=')).data.entries.some(e=>e.id===missingKey.data.id));
  // 9 Oct (VOICE): one take, one row; a take the helper saved while the node was away lands at the next sweep; a mic that
  // sends nothing is named on the Voice page; the watch reads the helper's real launchd job.
  const named='0f0e0d0c-0b0a-4908-8706-050403020100';
  const once=await api(`transcribe?quiet=1&app=Named&id=${named}`,fixture),twice=await api(`transcribe?quiet=1&app=Named&id=${named}`,fixture);
  check('a take named by the helper is written once, however often it arrives',once.status===200&&twice.status===200&&once.data.id===named&&twice.data.id===named&&(await api('history?q=')).data.entries.filter((e)=>e.id===named).length===1);
  const orphan='1f0e0d0c-0b0a-4908-8706-050403020101';mkdirSync(pend,{recursive:true});writeFileSync(path.join(pend,`${orphan}.json`),JSON.stringify({id:orphan,at:new Date().toISOString(),app:'Helper Saved',bundleId:'',tries:0}));writeFileSync(path.join(pend,`${orphan}.wav`),fixture);
  for(let i=0;i<40&&existsSync(path.join(pend,`${orphan}.wav`));i++)await sleep(150);
  check('a take the helper queued while the node was away lands at the next sweep, not the next deploy',(await api('history?q=')).data.entries.some((e)=>e.id===orphan&&e.app==='Helper Saved'));
  await api('transcribe?quiet=1',silentWav);await api('transcribe?quiet=1',silentWav);
  const sick=(await api('status')).data.health;
  check('takes of nothing at all say the mic sent nothing',sick?.level==='bad'&&/sent nothing/.test(sick.line));
  const takeLog=readFileSync(path.join(scratch,'dictation/takes.jsonl'),'utf8').trim().split('\n').map((l)=>JSON.parse(l));
  check('the take log has a line per take with outcome and loudness, never the words',takeLog.some((l)=>l.outcome==='silent'&&l.peakDb===-120)&&takeLog.some((l)=>l.outcome==='duplicate')&&takeLog.some((l)=>l.outcome==='written'&&l.retry)&&!JSON.stringify(takeLog).includes('fake dictation'));
  const watch=await (await fetch(`${base}/api/voice/status`)).json();
  check('the voice watch reads the Agent Base helper and the sync job, not the retired runtime',watch.watching===true&&watch.services.map((x)=>x.label).join()==='com.siso.agent-base.voice,com.siso.voice-sync'&&!calls().some(([v,l])=>v==='kickstart'&&String(l).includes('agent-base.voice')));
  await page.setViewportSize({width:1440,height:960});await page.goto(base);await page.locator('.siso-app__rail-btn[aria-label^="Voice"]').first().click();
  const line=page.locator('[data-testid=voice-check]');await line.waitFor({timeout:8000}).catch(()=>{});
  check('the Voice page says plainly that the mic sent nothing',await line.getAttribute('data-level').catch(()=>null)==='bad'&&/sent nothing/.test(await line.textContent().catch(()=>'')));
  await page.screenshot({path:path.join(shots,'voice-check-bad-1440.png')});
  const vh=await (await fetch(`${base}/api/voice/history?limit=500`)).json(),mine=(vh.entries||[]).find((e)=>e.id===named);
  check('History keeps what he said before cleanup and how long he spoke',mine?.raw==='um a fake dictation for SISO'&&mine?.text==='A polished fake dictation for SISO.'&&typeof mine?.durationSeconds==='number');
  const st=await (await fetch(`${base}/api/voice/stats`)).json(),timed=vh.entries.filter((e)=>e.durationSeconds>=1&&e.words>0),tw=timed.reduce((n,e)=>n+e.words,0),ts=timed.reduce((n,e)=>n+e.durationSeconds,0),allWords=vh.entries.reduce((n,e)=>n+e.words,0);
  const wpmWant=ts>=60?Math.round(tw/(ts/60)):null;
  check('Stats count speed over seconds spoken, and time saved after the talking',timed.length>0&&st.wpm===wpmWant&&st.timeSavedMinutes===Math.max(0,Math.round(allWords/40-(wpmWant?allWords/wpmWant:0))));
  const diag=await api('diagnostics');
  check('diagnostics give the self-check, the last takes, the queue and the log, never the words',diag.status===200&&diag.data.health?.level&&diag.data.takes.length>0&&Array.isArray(diag.data.queue)&&Array.isArray(diag.data.log)&&!JSON.stringify(diag.data).includes('fake dictation'));
  const later='2f0e0d0c-0b0a-4908-8706-050403020102';writeFileSync(path.join(pend,`${later}.json`),JSON.stringify({id:later,at:new Date().toISOString(),app:'Retry Now',bundleId:'',tries:2,next:Date.now()+3600_000}));writeFileSync(path.join(pend,`${later}.wav`),fixture);
  const listed=(await api('diagnostics')).data.queue.some((q)=>q.id===later&&q.app==='Retry Now'&&q.tries===2);const retried=await api('retry',{});
  check('Retry now sends a waiting take at once, whatever its backoff said',listed&&retried.status===200&&!retried.data.queue.some((q)=>q.id===later)&&(await api('history?q=')).data.entries.some((e)=>e.id===later));
  const outboxLines=()=>readFileSync(path.join(scratch,'outbox.ndjson'),'utf8').trim().split('\n').length;const callsSlow=groqCalls,linesSlow=outboxLines();groqMode='slow';
  const slow=await api('transcribe?quiet=1&app=Slow%20Groq',fixture);groqMode='ok';await sleep(800);
  check('a take still waiting on Groq is never sent again by the sweep',slow.status===200&&groqCalls===callsSlow+1&&outboxLines()===linesSlow+1);
  await page.getByRole('navigation',{name:'Voice pages'}).getByRole('button',{name:/^Settings/}).click();const card=page.locator('[data-testid=voice-diagnostics]');await card.locator('tbody tr').first().waitFor({timeout:8000}).catch(()=>{});
  check('Settings shows Diagnostics: the self-check, the last takes, the queue, and no words',await card.locator('.vx-state[data-level]').count()===1&&await card.locator('tbody tr').count()>0&&await card.getByRole('button',{name:/Retry/}).isDisabled()&&!(await card.textContent()).includes('fake dictation'));
  await card.screenshot({path:path.join(shots,'voice-diagnostics-1440.png')});
  check('rollback releases hotkey and reloads all jobs',(await api('owner',{owner:'siso-voice'})).status===200&&!nativeOn&&JSON.parse(readFileSync(store)).length===3);
  stoppingFixture=spawn(process.execPath,['-e','setInterval(() => {}, 1000)'],{stdio:'ignore'});
  writeFileSync(pidFile,String(stoppingFixture.pid));
  check('takeover refuses an old runtime that has not exited',(await api('owner',{owner:'agent-base'})).status===409&&(await api('status')).data.owner==='siso-voice'&&JSON.parse(readFileSync(store)).length===3);
  stoppingFixture.kill('SIGTERM');rmSync(pidFile);
  nativeEnabled=false;await sleep(150);await api('native',{registered:false,permission:true});
  check('missing native acknowledgment rolls takeover back',(await api('owner',{owner:'agent-base'})).status===409&&(await api('status')).data.owner==='siso-voice'&&JSON.parse(readFileSync(store)).length===3);
  const logs=readFileSync(path.join(scratch,'dictation/ownership.jsonl'),'utf8').trim().split('\n').map(JSON.parse);
  check('both switch directions and failed takeover logged without voice content',logs.some((l)=>l.from==='siso-voice'&&l.to==='agent-base'&&l.outcome==='complete')&&logs.some((l)=>l.to==='siso-voice'&&l.outcome==='complete')&&logs.some((l)=>l.outcome==='rolled-back')&&!JSON.stringify(logs).includes('dictation for SISO'));
  const keyApi=async(method,body)=>{const r=await fetch(`${base}/api/voice/key`,{method,headers:{'content-type':'application/json'},body:body&&JSON.stringify(body)});const t=await r.text();replies.push(t);return {status:r.status,data:JSON.parse(t)};};
  const settingsBefore=readFileSync(settings,'utf8');
  const refused=await keyApi('POST',{key:'gsk_lab_bad_key_0123456789abcdef'}),junk=await keyApi('POST',{key:'not a key'});
  check('a key Groq refuses, or one that is not a key, is never saved',refused.status===400&&/refused/.test(refused.data.error)&&junk.status===400&&readFileSync(settings,'utf8')===settingsBefore);
  const good=await keyApi('POST',{key:'gsk_lab_good_key_0123456789abcdef'}),after=await keyApi('GET');
  check('a key Groq accepts is saved 0600 and never sent back',good.status===200&&after.data.saved===true&&after.data.source==='file'&&JSON.parse(readFileSync(settings,'utf8')).groq_api_key==='gsk_lab_good_key_0123456789abcdef'&&(statSync(settings).mode&0o777)===0o600&&!replies.some((t)=>t.includes('gsk_lab_good_key')));
  const removed=await keyApi('DELETE');check('Remove takes the key away',removed.data.saved===false&&!('groq_api_key' in JSON.parse(readFileSync(settings,'utf8'))));
  writeFileSync(settings,settingsBefore,{mode:0o600});
  check('no credential in API replies',!replies.some((text)=>text.includes('fake-dictation-key')));
} catch(e) {check(`harness: ${e.message}`,false);} finally {clearInterval(timer);await browser?.close();const exited=node&&node.exitCode===null&&node.signalCode===null?new Promise((r)=>{node.once('exit',r);setTimeout(r,20000);}):null;node?.kill('SIGTERM');stoppingFixture?.kill('SIGTERM');await exited;await new Promise((r)=>groq.close(r));rmSync(scratch,{recursive:true,force:true,maxRetries:5});}
const passed=results.filter(Boolean).length;console.log(JSON.stringify({passed,of:results.length}));if(passed!==results.length)process.exitCode=1;
