// Isolated API + rendered interaction evidence. No agent sockets or running jobs are touched.
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { suitePort, webkit } from './suite-runtime.mjs';
const root = path.resolve(import.meta.dirname,'../../..');
const scratch = mkdtempSync(path.join(tmpdir(),'.siso-ephemeral-fleet-board.'));
const runs = path.join(scratch,'runs'), fleets = path.join(scratch,'fleet');
mkdirSync(runs); mkdirSync(path.join(fleets,'logos'),{recursive:true});
writeFileSync(path.join(fleets,'logos','manifest.json'),JSON.stringify({name:'logos',parent:'KIKAS',machine:'local',jobs:[{id:'one',status:'done'}]}));
writeFileSync(path.join(fleets,'logos','one.out'),'RETURN\nSTATUS: done — fixture logo');
writeFileSync(path.join(runs,'unknown.meta.json'),JSON.stringify({name:'unknown-job',worker:'unknown-job',pid:0,started:Date.now()}));
const port = await suitePort(), webPort = await suitePort(), url = `http://127.0.0.1:${port}`;
const env = {...process.env,AB_PORT:String(port),AB_MINI_LANES:'0',AB_FLEET_STATE:fleets,AB_CODEX_RUNS:runs,AB_DISPATCH_FILE:path.join(scratch,'dispatch.jsonl'),AB_HERDR:`${process.execPath} ${path.join(root,'services/node/test/fake-herdr.mjs')}`,FAKE_HERDR_AGENTS:JSON.stringify([{name:'A0',agent:'siso',agent_status:'idle',cwd:path.join(scratch,'SISO_Workspace/SISO_Agents/agent-zero/siso-agent-zero'),pane_id:'w1:p1',terminal_id:'fixture-zero',terminal_title_stripped:'A0'},{name:'KIKAS',agent:'siso',agent_status:'idle',cwd:scratch,pane_id:'w1:p2',terminal_id:'fixture-kikas',terminal_title_stripped:'KIKAS'}]),AB_REGISTRY:path.join(scratch,'registry.json'),AB_STATE:path.join(scratch,'rows.json'),AB_HOSTS_DIR:path.join(scratch,'hosts'),AB_A0_SEAT:path.join(scratch,'seat.json'),AB_HUB_HOME:scratch,AB_A0_TASKS:path.join(scratch,'tasks'),AB_RESURRECT_DIR:path.join(scratch,'none'),AB_CONSOLE_EVENTS:path.join(scratch,'none.jsonl'),AB_CLAUDE_DIRS:scratch,AB_CODEX_DIRS:scratch};
const children=[];let browser;
const wait = async f => { for(let i=0;i<1200;i++){try{if(await f())return;}catch{}await new Promise(r=>setTimeout(r,100));}throw Error('fixture timeout');};
const board = async () => (await (await fetch(url+'/api/fleet-board')).json());
try {
  children.push(spawn(process.execPath,['--experimental-strip-types','--no-warnings','src/server.ts'],{cwd:path.join(root,'services/node'),env,stdio:'inherit'}));
  await wait(async()=> (await fetch(url+'/api/health')).ok);
  const data = await board();
  assert(data.groups.find(g=>g.id==='kikas').rows.some(r=>r.name==='logos/one'));
  assert(data.groups.find(g=>g.id==='unassigned').rows.some(r=>r.name==='unknown-job'));
  const patch={op:'workspace',workspaces:[{id:'kikas',order:1,color:'#123456',size:'L'},{id:'halo-operator',order:0}]};
  assert.equal((await fetch(url+'/api/registry',{method:'POST',body:JSON.stringify(patch)})).status,200);
  const saved=JSON.parse(readFileSync(env.AB_REGISTRY,'utf8')).workspaces.find(w=>w.id==='kikas');
  assert.equal(saved.color,'#123456');assert.equal(saved.size,'L');
  assert.equal((await fetch(url+'/api/fleet-board/output?id=fleet:laptop:logos:one')).status,200);
  assert.equal((await fetch(url+'/api/fleet-board/output?id=../../etc/passwd')).status,404);
  children.push(spawn('pnpm',['--filter','@agent-base/web','dev','--host','127.0.0.1'],{cwd:root,env:{...env,AB_NODE:String(port),AB_WEB_PORT:String(webPort)},stdio:'inherit'}));
  await wait(async()=>(await fetch(`http://127.0.0.1:${webPort}`)).ok);
  browser=await webkit.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}});
  await page.routeWebSocket('**/*',ws=>ws.close());
  await page.goto(`http://127.0.0.1:${webPort}`);
  await page.getByRole('tab',{name:'Fleet',exact:true}).click();
  await page.locator('[data-testid="fleet-board"] [data-workspace="kikas"]').waitFor();
  assert.equal(await page.locator('[data-workspace]').count(),8);
  const handle=page.getByRole('button',{name:'Drag HALO Operator'}), target=page.locator('[data-workspace="kikas"]');
  const a=await handle.boundingBox(), b=await target.boundingBox();
  await page.mouse.move(a.x+a.width/2,a.y+a.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:15});await page.mouse.up();
  await wait(async()=> (await board()).groups[0].id==='kikas');
  await page.getByLabel("Kika's size").selectOption('S');
  await wait(async()=> (await board()).groups.find(g=>g.id==='kikas').size==='S');
  await page.getByRole('button',{name:'From Agent Zero',exact:true}).click();
  assert.equal(await page.locator('[data-workspace="kikas"]').getAttribute('data-count'),'0');
  await page.getByRole('button',{name:'All',exact:true}).click();
  await page.locator('[data-workspace="kikas"]').getByRole('button',{name:/1 done.*show/}).click();
  await page.getByRole('button',{name:/logos\/one/}).click();
  await page.getByText(/STATUS: done — fixture logo/).waitFor();
  await page.reload();await page.getByRole('tab',{name:'Fleet',exact:true}).click();
  await page.locator('[data-workspace="kikas"][data-size="S"]').waitFor();
  assert.equal(JSON.parse(readFileSync(env.AB_REGISTRY,'utf8')).workspaces.find(w=>w.id==='kikas').size,'S');
  console.log('PASS: Fleet grouping, unknown ownership, registry persistence, output containment, WebKit reorder, resize, dispatcher filter, completed expansion, job open and reload');
} finally { await browser?.close(); for(const p of children.reverse())p.kill('SIGTERM'); }
