import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, renameSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import http from 'node:http';
import { createOwners, parseOwner, parseMini } from '../src/owners.ts';
const root = mkdtempSync(path.join(tmpdir(), '.siso-ephemeral-ab-owners.'));
process.on('exit', () => rmSync(root, { recursive: true, force: true }));
process.env.AB_HOSTS_DIR = path.join(root, 'empty-hosts');
const folder = path.join(root, 'owners'); mkdirSync(folder);
process.env.AB_OWNERS_DIR = folder;
process.env.AB_REGISTRY = path.join(root, 'registry.json');
writeFileSync(process.env.AB_REGISTRY, JSON.stringify({workspaces:[{id:'halo',name:'HALO',color:'#123456',nav:true}]}));
const record = (name, extra = {}) => ({name, title:`${name} mission`,workspace:'halo',subtitle:'Reading evidence',status:'researching',started:'2026-10-05T10:00:00Z',updated:'2026-10-05T12:00:00Z', findings:[{title:'Small',impact:'small'},null,{title:'Big',impact:'big',evidence:'https://example.com/proof'}], ...extra});
writeFileSync(path.join(folder,'OLD.json'),JSON.stringify(record('OLD')));
writeFileSync(path.join(folder,'NEW.json'),JSON.stringify(record('NEW',{updated:'2026-10-05T13:00:00Z'})));
writeFileSync(path.join(folder,'BROKEN.json'),'{');
writeFileSync(path.join(folder,'_a0.json'),JSON.stringify({picks:[{name:'OLD',why:'Closest to a win'}]}));
const reader = createOwners(folder);
let s = reader.snapshot();
assert.deepEqual(s.owners.map(o=>o.name),['OLD','NEW']);
assert.equal(s.owners[0].pick,'Closest to a win');
assert.deepEqual(s.owners[0].findings.map(f=>f.title),['Big','Small']);
assert.equal(s.warnings.length,1);
assert.equal(parseOwner(record('X',{page:'javascript:alert(1)',asks:[null,'Access'],started:'bad',subagents:[null,{name:'Worker'}]}),'X.json').page,null);
assert.throws(()=>parseOwner(record('X'),'Y.json'));
writeFileSync(path.join(folder,'OLD.json'),'{'); s=reader.snapshot();
assert.equal(s.owners[0].readError,true);
assert.equal(s.owners[0].title,'OLD mission');
writeFileSync(path.join(folder,'OLD.json'),JSON.stringify(record('OLD')));
console.log('PASS parser: pick ordering, impact ranking, malformed/partial files, last-good recovery, unsafe page URL, missing fields');
const { route } = await import('../src/routes/owners.route.ts');
const server = http.createServer((req,res)=> { const m=req.url.match(route.path); if(req.method==='GET' && m) route.handle(req,res,m); else res.writeHead(404).end(); });
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base = `http://127.0.0.1:${server.address().port}`;
const abort = new AbortController();
let stream;
try {
  const r=await fetch(base+'/api/owners'); assert.equal(r.status,200); const data=await r.json();
  assert.equal(data.owners.length,2); assert.equal(data.workspaces.find(w=>w.id==='halo').color,'#123456');
  assert.equal((await fetch(base+'/api/owners',{method:'POST'})).status,404);
  const response=await fetch(base+'/api/owners/events',{signal:abort.signal});
  assert.match(response.headers.get('content-type'),/text\/event-stream/);
  stream=response.body.getReader(); let buffer='';
  // A hosted-runtime refresh can publish between the initial snapshot and the file watch event.
  // Match the requested state within the same deadline, rather than assuming the next event's cause.
  async function event(matches = () => true) { const deadline = new Promise((_,rej)=>setTimeout(()=>rej(Error('watch timed out')),3000).unref()); return Promise.race([deadline,(async()=>{for(;;){const split=buffer.indexOf('\n\n');if(split>=0){const line=buffer.slice(0,split);buffer=buffer.slice(split+2);const value=JSON.parse(line.replace(/^data: /,''));if(matches(value))return value;continue;} const chunk=await stream.read();buffer+=new TextDecoder().decode(chunk.value);}})()]); }
  assert.equal((await event()).owners.length,2);
  writeFileSync(path.join(folder,'NEW.tmp'),JSON.stringify(record('NEW',{subtitle:'Finding landed',updated:new Date().toISOString()})));
  renameSync(path.join(folder,'NEW.tmp'),path.join(folder,'NEW.json'));
  assert.equal((await event(s=>s.owners.find(o=>o.name==='NEW')?.subtitle==='Finding landed')).owners.find(o=>o.name==='NEW').subtitle,'Finding landed');
  writeFileSync(path.join(folder,'NEW.json'),'{');
  assert.equal((await event(s=>s.owners.find(o=>o.name==='NEW')?.readError===true)).owners.find(o=>o.name==='NEW').readError,true);
  writeFileSync(path.join(folder,'NEW.json'),JSON.stringify(record('NEW',{subtitle:'Recovered'})));
  assert.equal((await event(s=>s.owners.find(o=>o.name==='NEW')?.subtitle==='Recovered')).owners.find(o=>o.name==='NEW').subtitle,'Recovered');
  renameSync(path.join(folder,'_a0.json'),path.join(folder,'picks.archived'));
  assert.equal((await event(s=>s.owners.every(o=>o.pick===null))).owners.every(o=>o.pick===null),true);
  console.log('PASS endpoint: HTTP 200, read-only route, registry colours, SSE atomic rename, malformed update, recovery and picks removal');
} finally { abort.abort(); reader.close(); server.closeAllConnections(); await new Promise(r=>server.close(r)); }
const missing = createOwners(path.join(root,'late','owners'));
let updates=0, latest;
const stop=missing.subscribe(s=>{updates++;latest=s;});
assert.deepEqual(missing.snapshot().owners,[]);
async function until(check) { const deadline=Date.now()+15_000; while(!check() && Date.now()<deadline) await new Promise(r=>setTimeout(r,100)); assert.ok(check(),'watch update not observed'); }
mkdirSync(path.join(root,'late'));
await until(()=>updates>=2);
mkdirSync(path.join(root,'late','owners'));
await until(()=>updates>=3);
writeFileSync(path.join(root,'late','owners','LATE.json'),JSON.stringify(record('LATE')));
await until(()=>!!latest?.owners.length);
assert.ok(updates>=2); assert.equal(latest.owners[0].name,'LATE'); stop(); missing.close();
console.log('PASS absent folder: empty state and event-driven discovery when owners begin reporting');

// Mini manifests are fetched once for all visible subscribers, never by snapshot/read-only info pages.
let clock = 1_800_000_000_000, calls = 0, fail = false;
const name = 'oracle-build/01-recovery';
writeFileSync(path.join(folder,'oracle-build--01-recovery.json'),JSON.stringify(record(name,{parent:'OLD',machine:'mini',status:'blocked',model:'gpt-6-astra',fleet:'oracle-build',job:'01-recovery',branch:'codex/recovery',report:'/reports/RETURN.md',locks:['shared.ts']})));
const locksFile = path.join(root,'locks.json');
writeFileSync(locksFile,JSON.stringify({locks:[{owner:name,parent:'OLD',repo:'oracle',branch:'codex/recovery',files:['shared.ts'],mode:'own branch only'}],rules:['oracle-build: cold review before landing','OTHER: unrelated']}));
const mini = createOwners(folder,{now:()=>clock,locksFile,fetchMini:async()=>{ calls++; if(fail)throw Error('offline'); return [{name:'oracle-build',jobs:[{id:'01-recovery',status:'done',peak_rss_bytes:1234,started_ns:clock*1e6,ended:new Date(clock+1000).toISOString()}]}]; }});
assert.equal(mini.snapshot().owners.find(o=>o.name===name).parent,'OLD');
const plain = mini.subscribe(()=>{});await mini.refreshMini();assert.equal(calls,0);
const visible = mini.subscribe(()=>{},true);
await new Promise(r=>setImmediate(r));
assert.equal(calls,1);
let child=mini.snapshot().owners.find(o=>o.name===name);
assert.equal(child.status,'blocked');assert.equal(child.runtime.status,'done');assert.equal(child.runtime.peakRss,1234);
assert.equal(child.model,'gpt-6-astra');assert.deepEqual(child.locked[0].files,['shared.ts']);assert.deepEqual(child.rules,['oracle-build: cold review before landing']);
assert.equal(mini.snapshot().owners.find(o=>o.name==='OLD').locked.length,1);
await mini.refreshMini();assert.equal(calls,1);
visible();clock+=60_001;await mini.refreshMini();assert.equal(calls,1);
const resumed=mini.subscribe(()=>{},true);await new Promise(r=>setImmediate(r));assert.equal(calls,2);
clock+=60_001;fail=true;await mini.refreshMini();assert.equal(calls,3);assert.ok(mini.snapshot().mini.error);assert.equal(mini.snapshot().owners.find(o=>o.name===name).runtime.status,'done');
writeFileSync(locksFile,'{');assert.ok(mini.snapshot().warnings.some(w=>w.includes('Locks')));assert.equal(mini.snapshot().owners.find(o=>o.name===name).locked.length,1);
resumed();plain();mini.close();
assert.throws(()=>parseOwner(record('../bad'),'..--bad.json'));
console.log('PASS Mini: slash-name mapping, nested metadata, shared minute cache, no inactive reads, resume, failed fetch keeps cache, locks/rules and partial locks recovery');

const dated = parseMini([{name:'utc-mini',jobs:[{id:'job',status:'done',started:'2026-10-05T15:00:00',started_ns:Date.parse('2026-10-05T15:00:00Z')*1e6,ended:'2026-10-05T16:00:00'}]}]).get('utc-mini/job');
assert.equal(dated.ended,'2026-10-05T16:00:00.000Z');
console.log('PASS Mini timestamps: naive Mini end time derives its timezone from the manifest start epoch');

// Hosted observations cannot replace reported work, leak routing records, or guess identity.
let hostClock = 1_800_000_000_000, hostCalls = 0, hostFail = false, resolveHost;
const host = (name, extra = {}) => ({ name, state: 'live', activity: 'idle', model: 'gpt-6-astra', updatedAt: hostClock - 1000, token: 'SECRET_NEVER_EXPORT', port: 9999, pid: 123, session: 'PRIVATE_SESSION', cwd: '/private/work', context: { private: true }, ...extra });
let hosts = [host('OLD'), host('NEW', { activity: 'working' }), host('DUP'), host('DUP'), host('DOWN', { state: 'down', activity: 'working' }), host('CASE'), host('RESTART', { state: 'restarting' })];
for (const [name, status] of [['OLD','building'],['NEW','done'],['DUP','building'],['DOWN','building'],['ABSENT','researching'],['case','building'],['RESTART','blocked']]) writeFileSync(path.join(folder, name + '.json'), JSON.stringify(record(name, { status })));
const hosted = createOwners(folder, { now: () => hostClock, readServiceHosts: async () => { hostCalls++; if (hostFail) throw Error('SECRET_NEVER_EXPORT'); if (resolveHost === null) await new Promise(r => { resolveHost = r; }); return { hosts, publicHosts: [] }; } });
assert.equal(hosted.snapshot().owners.find(o => o.name === 'OLD').hostedRuntime.availability, 'unknown');
await hosted.refreshHosts(); assert.equal(hostCalls, 0);
resolveHost = null;
const stopHosted = hosted.subscribe(() => {}), stopSecond = hosted.subscribe(() => {});
assert.equal(hostCalls, 1); const pending = hosted.refreshHosts(); assert.equal(hostCalls, 1); resolveHost(); await pending;
const byName = name => hosted.snapshot().owners.find(o => o.name === name);
assert.equal(byName('OLD').status, 'building'); assert.equal(byName('OLD').hostedRuntime.activity, 'idle');
assert.equal(byName('NEW').status, 'done'); assert.equal(byName('NEW').hostedRuntime.activity, 'working');
assert.equal(byName('DOWN').hostedRuntime.availability, 'offline'); assert.equal(byName('DOWN').hostedRuntime.activity, 'unknown');
assert.equal(byName('RESTART').hostedRuntime.availability, 'restarting');
for (const name of ['ABSENT','DUP','case']) assert.equal(byName(name).hostedRuntime.availability, 'unknown');
assert.deepEqual(Object.keys(byName('OLD').hostedRuntime).sort(), ['activity','availability','metadataUpdatedAt','model','observedAt']);
assert.equal(byName('OLD').hostedRuntime.observedAt, hostClock);
assert.equal(byName('OLD').hostedRuntime.metadataUpdatedAt, hostClock - 1000);
assert.doesNotMatch(JSON.stringify(hosted.snapshot()), /SECRET_NEVER_EXPORT|PRIVATE_SESSION|private.work|"port"|"token"|"pid"|"hosts"/);
await hosted.refreshHosts(); assert.equal(hostCalls, 1);
hostClock += 15_001; hostFail = true; await hosted.refreshHosts();
assert.match(hosted.snapshot().hosted.error, /stale/); assert.equal(byName('OLD').hostedRuntime.observedAt, hostClock - 15_001);
assert.equal(byName('OLD').hostedRuntime.activity, 'idle'); assert.equal(byName('OLD').status, 'building');
stopHosted(); stopSecond(); hostClock += 15_001; await hosted.refreshHosts(); assert.equal(hostCalls, 2);
hostFail = false; hosts = [host('OLD', { activity: 'working' })];
const stopResume = hosted.subscribe(() => {}); await hosted.refreshHosts(); assert.equal(hostCalls, 3); assert.equal(hosted.snapshot().hosted.error, null);
assert.equal(byName('OLD').hostedRuntime.activity, 'working'); stopResume(); hosted.close();
console.log('PASS hosted runtime: exact unambiguous names, unknown/duplicate/offline/restarting, reported status preserved, five-field allowlist, coalesced visible cache, stale failure, unsubscribe and resume');
