import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import { realpathSync, mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { readProductMap, saveSurfaceRating, productMapPath, handleProductMap } from '../src/product-map.ts';
import { createServer } from 'node:http';
const root=realpathSync(mkdtempSync(path.join(tmpdir(),'product-map-fixture-')));
const cleanup=[root];process.on('exit',()=>{for(const folder of cleanup)rmSync(folder,{recursive:true,force:true});});
writeFileSync(path.join(root,'components.json'),JSON.stringify({components:[{id:'chat',name:'Chat',pages:[{id:'feedback',title:'Feedback',file:'FEEDBACK.md'},{id:'round',title:'Round',kind:'gallery',file:'rounds/one/'}]},{id:'library',name:'Library',kind:'page',pages:[]},{id:'tasks',kind:'page',pages:[],proofRefs:[{component:'chat',id:'linked-round',title:'Existing round',file:'rounds/one/'},{component:'chat',id:'escape',file:'../../outside/'}]},{id:'states',kind:'manual',pages:[]}]}));
mkdirSync(path.join(root,'chat/rounds/one'),{recursive:true});
// Catalog ingestion now fails closed instead of silently discarding an unsafe proof reference.
assert.throws(()=>readProductMap({hubRoot:root}),/Invalid catalog path/);
const validCatalog=JSON.parse(readFileSync(path.join(root,'components.json'),'utf8'));
validCatalog.components[2].proofRefs.pop();
writeFileSync(path.join(root,'components.json'),JSON.stringify(validCatalog));
writeFileSync(path.join(root,'chat/FEEDBACK.md'),'# Synthetic feedback\n');
writeFileSync(path.join(root,'chat/rounds/one/after.png'),'synthetic image');
writeFileSync(path.join(root,'chat/rounds/one/before.png'),'synthetic before');
writeFileSync(path.join(root,'chat/surface.json'),JSON.stringify({lane:'next',openFeedback:2,custom:'preserve'}));
const options={hubRoot:root,tasks:[{id:'t-1',title:'Fixture linked work',stage:'working',agent:'Fixture builder',links:{surface:'chat'}},{id:'t-2',title:'Unlinked work',stage:'working',links:{surface:'other'}}]};
const initial=readProductMap(options);
assert.equal(initial.rows.length,3);assert.equal(initial.rows[2].rounds.length,1);assert.match(initial.rows[2].screenshot.file,/chat\/rounds\/one\/after.png$/); assert.equal(initial.rows[0].rating,null);assert.equal(initial.rows[0].active.length,1);assert.equal(initial.rows[0].rounds.length,1);assert.equal(initial.rows[0].openFeedback,2);assert.match(initial.rows[0].screenshot.file,/after.png$/);assert.equal(initial.rows[1].screenshot,null);
const imageHash=createHash('sha256').update('synthetic image').digest('hex');
const captureRecord={schema:1,file:'chat/rounds/one/after.png',sha256:imageHash,capturedAt:'2026-10-06T00:00:00Z',mode:'synthetic',sourceRevision:'a'.repeat(40),sources:[{file:'apps/web/src/components/ChatView.tsx',sha256:'b'.repeat(64)}]};
writeFileSync(path.join(root,'chat/capture.json'),JSON.stringify(captureRecord));
writeFileSync(path.join(root,'chat/rounds/one/z-newer.png'),'newer legacy image without capture provenance');
let captured=readProductMap(options).rows[0];assert.equal(captured.screenshot.sha256,imageHash);assert.equal(captured.screenshot.file,'chat/rounds/one/after.png');assert.equal(captured.screenshot.mode,'synthetic');assert.match(captured.screenshot.evidence,/installed behavior unverified/);assert.equal(captured.rating,null);assert.equal(captured.pages.at(-1).id,'capture-provenance');
const interval={precision:'interval',startAt:'2026-10-06T00:50:41.973Z',endAt:'2026-10-06T00:54:52.948Z'};
writeFileSync(path.join(root,'chat/capture.json'),JSON.stringify({...captureRecord,capturedAt:undefined,captureInterval:interval}));
captured=readProductMap(options).rows[0];assert.equal(captured.screenshot.capturedAt,undefined);assert.deepEqual(captured.screenshot.captureInterval,interval);assert.match(captured.screenshot.evidence,/Captured during 2026-10-06T00:50:41\.973Z/);
writeFileSync(path.join(root,'chat/capture.json'),JSON.stringify({...captureRecord,capturedAt:undefined,captureInterval:{...interval,endAt:'2026-10-05T00:00:00Z'}}));
assert.match(readProductMap(options).rows[0].issues.join(' '),/provenance invalid/);
writeFileSync(path.join(root,'chat/capture.json'),JSON.stringify({...captureRecord,sha256:'c'.repeat(64)}));
captured=readProductMap(options).rows[0];assert.equal(captured.screenshot.sha256,undefined);assert.match(captured.issues.join(' '),/hash changed/);
writeFileSync(path.join(root,'chat/capture.json'),JSON.stringify({...captureRecord,file:'chat/link/escape.png'}));assert.match(readProductMap(options).rows[0].issues.join(' '),/provenance invalid/);
writeFileSync(path.join(root,'chat/capture.json'),JSON.stringify(captureRecord));
const saved=saveSurfaceRating('chat',{rating:'ok',note:'Synthetic test verdict only'},options);
assert.deepEqual(readProductMap(options).rows[0].rating,saved);assert.equal(JSON.parse(readFileSync(path.join(root,'chat/surface.json'))).custom,'preserve');
saveSurfaceRating('library',{rating:'good',note:'Synthetic new directory'},options);assert.equal(readProductMap(options).rows[1].rating.value,'good');
for(const id of ['../escape','%2e%2e','CHAT','missing','states'])assert.throws(()=>saveSurfaceRating(id,{rating:'good',note:''},options));
for(const input of [{rating:'approved',note:''},{rating:'good',note:9},{rating:'ok',note:'x'.repeat(4001)},null])assert.throws(()=>saveSurfaceRating('chat',input,options));
for(const rel of ['../escape','/escape','chat/../../escape','chat/%2e%2e/escape','chat\\escape','chat//escape'])assert.throws(()=>productMapPath(root,rel));
const outside=realpathSync(mkdtempSync(path.join(tmpdir(),'product-map-outside-')));
cleanup.push(outside);symlinkSync(outside,path.join(root,'chat/link'));assert.throws(()=>productMapPath(root,'chat/link/anything'));
symlinkSync(outside,path.join(root,'symlink-root'));assert.throws(()=>productMapPath(path.join(root,'symlink-root'),'anything'));
assert.equal(readProductMap({hubRoot:root}).taskAvailability,'unavailable');
writeFileSync(path.join(root,'chat/surface.json'),'{bad');assert.equal(readProductMap(options).rows[0].rating,null);assert.throws(()=>saveSurfaceRating('chat',{rating:'shit',note:''},options));
writeFileSync(path.join(root,'chat/surface.json'),JSON.stringify({padding:'x'.repeat(253000)}));assert.throws(()=>saveSurfaceRating('chat',{rating:'ok',note:'n'.repeat(4000)},options));
writeFileSync(path.join(root,'chat/surface.json'),'{}');
const server=createServer((req,res)=>void handleProductMap(req,res,options));await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
try{
 assert.equal((await fetch(base+'/api/product-map')).status,200);
 const response=await fetch(base+'/api/product-map/chat/rating',{method:'POST',body:JSON.stringify({rating:'shit',note:'HTTP fixture only 🧭'})});assert.equal(response.status,200);
 const reloaded=(await(await fetch(base+'/api/product-map')).json()).rows[0].rating;assert.equal(reloaded.value,'shit');assert.equal(reloaded.note,'HTTP fixture only 🧭');
 assert.equal((await fetch(base+'/api/product-map/chat/rating',{method:'POST',body:'x'.repeat(9000)})).status,413);
 assert.equal((await fetch(base+'/api/product-map/files/chat/%2e%2e%2foutside.md')).status,503);
 assert.equal((await fetch(base+'/api/product-map/files/chat/link/anything.md')).status,503);
 assert.equal((await fetch(base+'/api/product-map/tasks/t-1')).status,200);
 assert.equal((await fetch(base+'/api/product-map/tasks/t-2')).status,404);
 assert.equal((await fetch(base+'/api/product-map/files/chat/rounds/one/')).status,200);
 console.log('PASS product-map: persisted reload, catalog coverage, missing metadata, explicit running links, bounds, traversal/symlink refusal, HTTP save/readback. Synthetic temporary state only.');
}finally{await new Promise(r=>server.close(r));}
