import assert from 'node:assert/strict';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(path.resolve(import.meta.dirname,'../../../apps/web/package.json'));
const viteRequire=createRequire(require.resolve('vite'));
const {build}=viteRequire('esbuild');
const {outputFiles}=await build({entryPoints:[path.resolve(import.meta.dirname,'../../../apps/web/src/lib/project-page.ts')],bundle:true,write:false,platform:'node',format:'esm',logLevel:'silent'});
const {projectTaskRows,projectTaskLane,projectEntity,projectWithEntityOwner}=await import(`data:text/javascript;base64,${Buffer.from(outputFiles[0].text).toString('base64')}`);
const root={id:'p',title:'Parent',stage:'building',owner:'INTEGRATOR',agent:'WORKER',project:'p',priority:'P1',updated:'',model:null};
const child={...root,id:'s',parent:'p',agent:'SPECIALIST'};
assert.deepEqual(projectTaskRows([root,child],'SPECIALIST').map(t=>t.id),['p']);
assert.deepEqual(projectTaskRows([root,child],'OTHER'),[]);
assert.deepEqual(projectTaskRows([root,child],null).map(t=>t.id),['p']);
assert.equal(projectTaskLane({...root,needs:true}),'Blocked');
assert.equal(projectTaskLane({...root,stage:'live',source:'unavailable'}),'Unavailable','unreadable is not completion or a work blocker');
assert.equal(projectTaskLane({...root,stage:'specced'}),'Next');
assert.equal(projectTaskLane({...root,stage:'specced',next:'NOW: begin'}),'Now');
assert.equal(projectTaskLane({...root,stage:'live'}),'Done');
assert.equal(projectTaskLane({...root,stage:'dropped'}),'Dropped');
const p={id:'p',name:'Project',group:'labs',owners:[{name:'OFFLINE',main:true},{name:'LIVE',domain:'Current owner'}]};
assert.equal(projectEntity(p).owner.sentence,'Owner offline');
assert.equal(projectEntity(p,{name:'LIVE',status:'working'}).owner.name,'LIVE');
assert.equal(projectEntity(p,{name:'LIVE',status:'working'}).owner.why.text,'Current owner');
assert.deepEqual(projectEntity(p).stats,[]);
const entity=projectEntity(p,{name:'LIVE',status:'working'});
assert.equal(projectWithEntityOwner({...p,owners:[]},entity).owners[0].name,'LIVE');
assert.equal(projectWithEntityOwner({...p,owners:[]},{...entity,owner:{...entity.owner,mode:'record',name:'Person on record',planned:null}}).owners.length,0,'human record is not an agent session');
const cycle=[{...root,parent:'s'},{...child,parent:'p'}];
assert.doesNotThrow(()=>projectTaskRows(cycle,'SPECIALIST'));
console.log('PASS project page: filtered ancestry, owner/executor identity, task lanes, offline and unknown sources');
