// Exact accounting and responsiveness on synthetic history; never a live home/session.
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, appendFileSync, renameSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
const dir = mkdtempSync(path.join(tmpdir(), '.siso-ephemeral-reconnect-hud.'));
process.env.HOME = dir;
const { seatHud } = await import('../src/seat-hud.ts');
const file = path.join(dir, 'claude/projects/seat.jsonl'), ctx = path.join(dir,'ctx');
mkdirSync(path.dirname(file), {recursive:true});mkdirSync(ctx);
const line = (id, output=20) => JSON.stringify({type:'assistant',message:{id,model:'claude-opus-5-5',usage:{input_tokens:100,cache_read_input_tokens:900,output_tokens:output},content:[{type:'text',text:'Synthetic 🌟 accounting'}]}})+'\n';
writeFileSync(file,line('same').repeat(50000)+line('same',30));
const background = () => seatHud(file,ctx,undefined,undefined,{background:true});
const until = async fn => { for(let i=0;i<1000;i++){const v=fn();if(v)return v;await new Promise(r=>setTimeout(r,10));}throw Error('HUD scan timeout'); };
assert.equal(background(),null,'cold HUD must not delay the list');
let ticks=0;const timer=setInterval(()=>ticks++,1);
const first = await until(background);clearInterval(timer);
assert.ok(ticks>2,'timers run throughout historical accounting');
assert.equal(first.total_input_tokens,1000);assert.equal(first.total_output_tokens,30);
assert.equal(first.used_percentage,null,'unknown context window stays unknown');
console.log('PASS cold background read yields; repeated API records count once; larger repeated output wins');
const bytes=Buffer.from(line('unicode-🌟',40)), split=bytes.indexOf(Buffer.from('🌟'))+1;
appendFileSync(file,bytes.subarray(0,split));
await new Promise(r=>setTimeout(r,50));background();await new Promise(r=>setTimeout(r,50));
assert.equal(background().total_output_tokens,30,'partial Unicode record waits');
appendFileSync(file,bytes.subarray(split));
const appended=await until(()=>{const v=background();return v?.total_output_tokens===70 && v;});
assert.equal(appended.total_input_tokens,2000);
console.log('PASS incremental append and split UTF-8 record remain exact');
const replacement=path.join(dir,'replacement');writeFileSync(replacement,line('replacement',90));renameSync(replacement,file);
const replaced=await until(()=>{const v=background();return v?.total_output_tokens===90 && v;});assert.equal(replaced.total_input_tokens,1000);
writeFileSync(file,line('truncated',1));
await until(()=>background()?.total_output_tokens===1);
console.log('PASS file replacement and truncation discard old totals');
const missing=seatHud(path.join(dir,'missing'),ctx,undefined,undefined,{background:true});assert.equal(missing,null);
console.log('PASS missing history does not throw or block');
