import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createSpaces, spaceAgents } from '../src/spaces.ts';
const root=mkdtempSync(path.join(tmpdir(),'ab-spaces-test-'));
const spaces=createSpaces(root), project='agent-base';
mkdirSync(path.join(root,project,'pins'),{recursive:true});
writeFileSync(path.join(root,project,'pins','research.md'),'---\ntitle: What we found\nkind: note\nby: Research\nat: 2026-10-05\n---\nKeep the useful result.');
assert.equal(spaces.read(project,[]).pins[0].title,'What we found');
writeFileSync(path.join(root,project,'pins','new.md'),'---\ntitle: Arrived on next poll\n---\nNew result');
assert.equal(spaces.read(project,[]).pins.length,2);
spaces.patch(project,{positions:{'agent:laptop/OWNER':{x:-40,y:21}}});
spaces.patch(project,{positions:{'pin:research':{x:100,y:-300}},collapsed:{'agent:laptop/RESEARCH':true}});
assert.equal(createSpaces(root).read(project,[]).layout.positions['agent:laptop/OWNER'].x,-40);
assert.equal(spaces.read(project,[]).layout.collapsed['agent:laptop/RESEARCH'],true);
assert.throws(()=>spaces.patch(project,{positions:{broken:{x:Infinity,y:0}}}),/finite/);
assert.throws(()=>spaces.read('../escape',[]),/Invalid project/);
assert.throws(()=>spaces.addPin(project,{title:'',markdown:'x'}),/requires/);
const pin=spaces.addPin(project,{title:'Saved by Shaan',markdown:'[Evidence](https://example.com)',kind:'link'});
assert.equal(spaces.read(project,[]).pins.find(p=>p.id===pin.id).by,'Shaan');
const repo=path.join(root,'repo');mkdirSync(repo);writeFileSync(path.join(repo,'SPEC.md'),'# A real repo document');
spaces.addPin(project,{title:'Spec',kind:'doc',path:'SPEC.md',markdown:''});
assert.ok(spaces.read(project,[],repo).pins.some(p=>p.markdown==='# A real repo document'));
spaces.addPin(project,{title:'Outside',kind:'doc',path:'../outside.md',markdown:''});
assert.ok(spaces.read(project,[],repo).pins.find(p=>p.title==='Outside').error);
writeFileSync(path.join(root,'secret.md'),'hidden');symlinkSync(path.join(root,'secret.md'),path.join(root,project,'pins','redirect.md'));
assert.ok(!spaces.read(project,[]).pins.some(p=>p.id==='redirect'));
writeFileSync(path.join(root,project,'pins','malformed.md'),'---\ntitle: {"bad":true}\nby: 12\n---\nStill safe to render');
assert.equal(typeof spaces.read(project,[]).pins.find(p=>p.id==='malformed').title,'string');
const members=spaceAgents('agent-base','Agent Base',[{id:'owner',name:'OWNER',project:'Agent Base'},{id:'child',name:'RESEARCH',parentId:'owner'},{id:'grandchild',name:'SCOUT',owner:'RESEARCH'},{id:'other',name:'OTHER',project:'HALO'}]);
assert.deepEqual(members.map(a=>a.id),['owner','child','grandchild']);
assert.ok(readFileSync(path.join(root,project+'.json'),'utf8').includes('pin:research'));
console.log('spaces: assertions passed (pins, next read, layout reload, doc bounds, symlink, membership)');
console.log('fixture state: '+root);
