// Failed uploads retain the requested message; retry/remove needs a fresh explicit Send.
import { spawn } from "node:child_process";
import { createServer } from "node:net";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { webkit } from './suite-runtime.mjs';

const REPO = path.join(import.meta.dirname, "../../.."); const reserve = createServer();
await new Promise((resolve, reject) => reserve.once("error", reject).listen(0, "127.0.0.1", resolve)); const PORT = reserve.address().port; await new Promise((resolve) => reserve.close(resolve)); const BASE = `http://127.0.0.1:${PORT}`;
mkdirSync(path.join(REPO, ".lab-pair/tmp"), { recursive: true });
const scratch = mkdtempSync(path.join(REPO, ".lab-pair/tmp", ".siso-ephemeral-upload-fail.")); const claude = path.join(scratch, "claude"); const project = path.join(claude, "projects", "fixture"); mkdirSync(project, { recursive: true });
const sessions = { alpha: "stream-alpha", beta: "stream-beta" }; for (const [name, session] of Object.entries(sessions)) writeFileSync(path.join(project, `${session}.jsonl`), JSON.stringify({ type: "user", uuid: `${name}-ready`, timestamp: new Date().toISOString(), message: { role: "user", content: `${name} ready` } }) + "\n");
const agentsFile = path.join(scratch, "agents.json"); const rec = (name, pane, terminal_id, session) => ({ agent: "claude", agent_status: "working", cwd: "/tmp", pane_id: pane, terminal_id, terminal_title_stripped: name, agent_session: { value: session } });
writeFileSync(agentsFile, JSON.stringify([rec("ALPHA", "w1:p2", "term-stream-alpha", sessions.alpha), rec("BETA", "w1:p3", "term-stream-beta", sessions.beta)])); writeFileSync(path.join(scratch, "registry.json"), JSON.stringify({ projects: [], agents: { ALPHA: { project: "Fixture", kind: "owner", domain: "Fixture" }, BETA: { project: "Fixture", kind: "owner", domain: "Fixture" } }, domains: [] }));
const env = { PATH: process.env.PATH, TMPDIR: process.env.TMPDIR, LANG: process.env.LANG, SHELL: process.env.SHELL, HOME: scratch, AB_HOME: scratch, CODEX_HOME: path.join(scratch, ".codex"), AB_CODEX_HOME: path.join(scratch, ".codex"), CLAUDE_CONFIG_DIR: path.join(scratch, ".claude"), XDG_CONFIG_HOME: path.join(scratch, ".config"), XDG_CACHE_HOME: path.join(scratch, ".cache"), XDG_DATA_HOME: path.join(scratch, ".local/share"), XDG_STATE_HOME: path.join(scratch, ".local/state"), AB_PORT: String(PORT), AB_HUB_HOME: scratch, AB_ORG_HOME: scratch, AB_ROLODEX_HOME: scratch, AB_CLAUDE_DIRS: claude, AB_CTX_DIR: path.join(scratch, "ctx"), AB_HUD_DIR: path.join(scratch, "ctx"), AB_HERDR: `${process.execPath} ${path.join(REPO, "services/node/test/fake-herdr.mjs")}`, FAKE_HERDR_AGENTS_FILE: agentsFile, AB_HOSTS_DIR: path.join(scratch, "hosts"), AB_STATE: path.join(scratch, "rows.json"), AB_REGISTRY: path.join(scratch, "registry.json"), AB_RESURRECT_DIR: path.join(scratch, "none"), AB_CONSOLE_EVENTS: path.join(scratch, "none.jsonl"), AB_OPEN_DRY: "1", AB_CONSOLE_URL: BASE, AB_BURN_CMD: "true", AB_VOICE_DB: path.join(scratch, "voice.db"), AB_VOICE_PREFS: path.join(scratch, "voice.plist"), AB_VOICE_WATCH: "0" };
writeFileSync(path.join(REPO,".lab-pair/upload-fail-results.jsonl"), "");
const results=[];const check=(name,ok,detail={})=>{results.push(!!ok);const result=JSON.stringify({check:name,ok:!!ok,...detail});writeFileSync(path.join(REPO,".lab-pair/upload-fail-results.jsonl"),result+"\n",{flag:"a"});console.log(result);};const sleep=ms=>new Promise(r=>setTimeout(r,ms));const until=async(fn,ms=5000)=>{for(const end=Date.now()+ms;Date.now()<end;await sleep(50))if(await fn())return true;return false;};let node,browser;const png=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/4Rr4WQAAAABJRU5ErkJggg==","base64");
try {
 node=spawn(process.execPath,["--experimental-strip-types","--no-warnings","src/server.ts"],{cwd:path.join(REPO,"services/node"),env,stdio:"ignore"});check("isolated node health",await until(async()=>(await fetch(`${BASE}/api/health`).catch(()=>null))?.ok,15000));browser=await webkit.launch();
 for(const c of [{name:"both-success",statuses:[201,201],order:[1,0]},{name:"failed-first",statuses:[500,201],order:[0,1]},{name:"failed-last",statuses:[201,500],order:[0,1]},{name:"malformed-response",statuses:[201,200],order:[0,1]},{name:"network-error",statuses:[201,0],order:[0,1]}]){
  const context=await browser.newContext({viewport:{width:1280,height:900}});const requests=[],release=[],settled=[],messages=[],errors=[],external=[];
  const gates=[0,1].map(i=>new Promise(r=>release[i]=r));
  await context.route("**/*",async r=>{const u=new URL(r.request().url());if(u.origin!==BASE){external.push(u.origin);return r.abort();}if(u.pathname!=="/api/uploads")return r.continue();const i=requests.length;requests.push({method:r.request().method(),type:r.request().headers()["content-type"]});if(i>1)return r.fulfill({status:201,contentType:"application/json",body:JSON.stringify({path:"/fixture/retried.png",name:"retried.png"})});await gates[i];if(c.statuses[i]===0){settled.push(i);return r.abort();}await r.fulfill({status:c.statuses[i],contentType:"application/json",body:JSON.stringify(c.statuses[i]===201?{path:`/fixture/image-${i}.png`,name:`image-${i}.png`}:{error:"fixture upload too large"})});settled.push(i);});
  const page=await context.newPage();page.on("pageerror",e=>errors.push(e.message));await page.routeWebSocket(/\/chat\/[^/]+\/ws/,ws=>{const id=decodeURIComponent(new URL(ws.url()).pathname.split("/")[2]);ws.onMessage(m=>messages.push({id,...JSON.parse(String(m))}));ws.send(JSON.stringify({t:"hello",session:id,log:[],before:0,more:false,state:"idle",thinking:{},partial:{},tasks:[],bg:[]}));});
  await page.addInitScript(()=>{localStorage.setItem('agent-base:active',JSON.stringify('term-stream-alpha'));localStorage.setItem('agent-base:open',JSON.stringify(['term-stream-alpha']));});await page.goto(BASE);const view=page.locator('[data-testid="chat-view"]:visible');const editor=view.getByRole("textbox",{name:"Message",exact:true});await editor.waitFor();const draft=`TWO-IMAGE-${c.name}`;await view.locator('input[type=file]').setInputFiles([0,1].map(i=>({name:`image-${i}.png`,mimeType:"image/png",buffer:png})));await until(()=>requests.length===2);await editor.fill(draft);await view.getByRole("button",{name:"Send",exact:true}).click();const held=await until(async()=>(await view.innerText()).includes("Sends as soon as the image is added"));check(`${c.name}: two actual uploads gate Send`,held&&requests.length===2&&requests.every(r=>r.method==="POST"&&r.type==="image/png")&&messages.filter(m=>m.t==="prompt").length===0,{requests,held});
  release[c.order[0]]();await until(()=>settled.includes(c.order[0]));await page.waitForTimeout(250);check(`${c.name}: one settled upload cannot release Send`,messages.filter(m=>m.t==="prompt").length===0&&await editor.inputValue()===draft,{settled,draft:await editor.inputValue()});
  release[c.order[1]]();await until(()=>settled.length===2);await until(async()=>messages.some(m=>m.t==="prompt")||await view.getByTestId("upload-error").count()>0);await page.waitForTimeout(200);const sends=messages.filter(m=>m.t==="prompt");const observed=await editor.inputValue();
  if(c.statuses.every(s=>s===201)){check("both-success: exactly one prompt includes both images after both settle",sends.length===1&&sends[0].id==="term-stream-alpha"&&sends[0].text===draft&&JSON.stringify(sends[0].images)===JSON.stringify(c.order.map(i=>`/fixture/image-${i}.png`))&&observed==="",{sends,draft:observed});}
  else{check(`${c.name}: partial upload failure retains draft and does not send incomplete prompt`,sends.length===0&&observed===draft,{sends,draft:observed});check(`${c.name}: failed attachment has readable upload error`,(await view.getByTestId("upload-error").innerText()).includes("Didn't upload: retry or remove")&&(await view.innerText()).includes("Send canceled"));
  check(`${c.name}: successful attachment remains`,await view.locator('.siso-chat__attach img').count()===1);
  await view.getByRole("button",{name:"Send",exact:true}).click();await page.waitForTimeout(150);check(`${c.name}: explicit Send also blocks while image failed`,messages.filter(m=>m.t==="prompt").length===0&&await editor.inputValue()===draft);
  if(c.name!=="failed-first"){
    await view.getByRole("button",{name:/Retry upload/}).click();await until(async()=>await view.getByTestId("upload-error").count()===0);await page.waitForTimeout(200);
    check(`${c.name}: retry uploads the same file without releasing canceled Send`,requests.length===3&&requests[2].type==="image/png"&&messages.filter(m=>m.t==="prompt").length===0&&await editor.inputValue()===draft);
    await view.getByRole("button",{name:"Send",exact:true}).click();await until(()=>messages.some(m=>m.t==="prompt"));const prompt=messages.find(m=>m.t==="prompt");check(`${c.name}: fresh Send includes retained and retried images`,prompt?.text===draft&&JSON.stringify(prompt.images)===JSON.stringify(["/fixture/image-0.png","/fixture/retried.png"]));
  }else{
    await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(REPO,".lab-pair","upload-fail-narrow.png")});
    await view.getByRole("button",{name:/Remove failed image/}).click();await page.waitForTimeout(150);check("remove error does not release canceled Send",messages.filter(m=>m.t==="prompt").length===0&&await editor.inputValue()===draft);
    await view.getByRole("button",{name:"Send",exact:true}).click();await until(()=>messages.some(m=>m.t==="prompt"));const prompt=messages.find(m=>m.t==="prompt");check("fresh Send after remove includes retained image",prompt?.text===draft&&JSON.stringify(prompt.images)===JSON.stringify(["/fixture/image-1.png"]));
  }}
  await page.setViewportSize({width:390,height:844});const geometry=await page.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth}));check(`${c.name}: narrow composer has no page errors or external requests`,geometry.width<=geometry.viewport+1&&errors.length===0&&external.length===0,{geometry,errors,external});await context.close();
 }
}catch(e){check("two-image upload completion",false,{error:String(e?.stack??e).slice(0,900)});}finally{await browser?.close();if(node){node.kill();if(node.exitCode===null)await new Promise(r=>node.once("exit",r));}rmSync(scratch,{recursive:true,force:true});}console.log(JSON.stringify({passed:results.filter(Boolean).length,of:results.length}));process.exit(results.every(Boolean)?0:1);
