import assert from 'node:assert/strict';
import http from 'node:http';
import { once } from 'node:events';
import { readFileSync, mkdirSync, writeFileSync, statSync } from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { proxy, rolodexContacts } from '../src/whatsapp.ts';
import { accountKey, readOrganisation, organise, resolveIntake } from '../src/whatsapp-private.ts';
import { previewWhatsAppImport, importWhatsAppContacts, undoWhatsAppImport, list } from '../src/rolodex.ts';

assert(process.env.AB_WHATSAPP_STATE?.includes('.siso-ephemeral-'), 'requires isolated private fixture directory');
let mode = 'accept', sends = 0, calls = 0;
const person = { jid: 'synthetic@s.whatsapp.net', name: 'Avery Fixture', phone: '10000000001', isGroup: false, lastTs: 100, lastIn: 100, lastOut: 0, messages: 2, sent: 0 };
const gateway = http.createServer(async (req, res) => {
  calls++;
  res.setHeader('content-type', 'application/json');
  if (req.url === '/rolodex') return res.end(JSON.stringify({ people: [person, person] }));
  if (req.url === '/health') return res.end(JSON.stringify({ readReceipts: mode !== 'receipts-on' ? false : true }));
  if (req.url.endsWith('/send')) {
    sends++;
    const chunks=[]; for await (const c of req) chunks.push(c);
    const body = JSON.parse(Buffer.concat(chunks)); assert.deepEqual(Object.keys(body), ['text']);
    if (mode === 'reject') { res.statusCode=429; return res.end('{"error":"synthetic rejection"}'); }
    if (mode === 'unknown') { res.destroy(); return; }
    await new Promise(r=>setTimeout(r, 50));
    return res.end(JSON.stringify({ id: 'synthetic-message' }));
  }
  res.end('{}');
});
gateway.listen(0,'127.0.0.1'); await once(gateway,'listening');
const cfg={url:`http://127.0.0.1:${gateway.address().port}`,token:'synthetic-token'};
const app=http.createServer(async(req,res)=>{
  let body=''; for await (const c of req) body+=c;
  await proxy(req,res,new URL(req.url,'http://fixture'),cfg,req.headers.origin==='http://fixture',body || undefined);
});
app.listen(0,'127.0.0.1'); await once(app,'listening');
const base=`http://127.0.0.1:${app.address().port}/api/whatsapp`;
const post=async(route,input,origin='http://fixture')=>{
  const r=await fetch(base+route,{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(input)});
  return {status:r.status,body:await r.json()};
};
const route='/chats/synthetic%40s.whatsapp.net/send';
const input=()=>({text:'Synthetic acceptance message',requestId:randomUUID(),explicit:true});
try {
  assert.equal((await post(route,input(),'https://outside.invalid')).status,403); assert.equal(sends,0);
  assert.equal((await post(route,{...input(),explicit:false})).status,400); assert.equal(sends,0);
  assert.equal((await post(route,{...input(),requestId:'../../bad'})).status,400);
  assert.equal((await post(route,{...input(),text:'😀'.repeat(1001)})).status,400);
  const request=input();
  const responses=await Promise.all([post(route,request),post(route,request)]);
  assert.equal(sends,1); assert(responses.some(r=>r.status===200)); assert(responses.some(r=>r.status===409));
  assert.equal((await post(route,request)).body.replay,true); assert.equal(sends,1);
  assert.equal((await post(route,{...request,text:'changed'})).status,409); assert.equal(sends,1);
  mode='reject'; const retry=input(); assert.equal((await post(route,retry)).status,429);
  mode='accept'; assert.equal((await post(route,retry)).status,429); assert.equal(sends,2);
  assert.equal((await post(route,{...retry,requestId:randomUUID()})).status,200); assert.equal(sends,3);
  mode='unknown'; const unknown=input(); assert.equal((await post(route,unknown)).body.uncertain,true);
  mode='accept'; assert.equal((await post(route,unknown)).status,409); assert.equal(sends,4);
  const receipt=path.join(process.env.AB_WHATSAPP_STATE,accountKey(cfg.url),'sends',unknown.requestId+'.json');
  assert.equal(JSON.parse(readFileSync(receipt)).state,'unknown'); assert.equal(statSync(receipt).mode & 0o777,0o600);
  assert(!readFileSync(receipt,'utf8').includes(unknown.text));
  mode='receipts-on'; assert.equal((await post('/chats/synthetic/read',{})).status,403); mode='accept';
  const before=calls; assert.equal((await post('/not-allowed',{})).status,404); assert.equal(calls,before);
  let org=(await (await fetch(base+'/organisation')).json());
  assert.equal((await post('/organisation',{type:'pin',chat:person.jid,pinned:true,revision:org.revision},'https://outside.invalid')).status,403);
  org=(await post('/organisation',{type:'pin',chat:person.jid,pinned:true,revision:org.revision})).body;
  assert.equal(readOrganisation(accountKey(cfg.url)).pins[person.jid],true);
  assert.equal((await post('/organisation',{type:'pin',chat:person.jid,pinned:false,revision:0})).status,409);
  org=(await post('/organisation',{type:'folder',name:'Clients',revision:org.revision})).body;
  org=(await post('/organisation',{type:'folder',name:'Project Fixture',parent:org.folders[0].id,revision:org.revision})).body;
  org=(await post('/organisation',{type:'membership',chat:person.jid,folder:org.folders[1].id,member:true,revision:org.revision})).body;
  org=(await post('/organisation',{type:'save',chat:person.jid,message:'fixture-m1',saved:true,revision:org.revision})).body;
  assert.equal(org.folders[1].chats[0],person.jid); assert.equal(org.saved.length,1);
  assert.equal(readOrganisation(accountKey(cfg.url)).saved.length,1);
  assert.deepEqual(rolodexContacts(['Avery Fixture'],[person,{...person,jid:'other@lid'}]),[]);
  assert.equal(rolodexContacts(['Avery Fixture'],[person,person]).length,1);
  const importedPreview=await (await fetch(base+'/contacts/preview')).json();
  assert.equal(importedPreview.added,1);
  assert.equal((await post('/contacts/import',{revision:importedPreview.revision},'https://outside.invalid')).status,403);
  assert.equal((await post('/contacts/import',{revision:'stale'})).status,409);
  assert.equal((await post('/contacts/import',{revision:importedPreview.revision,selected:[person.jid]})).body.imported,1);
  const repeatedPreview=await (await fetch(base+'/contacts/preview')).json();
  assert.equal(repeatedPreview.unchanged,1);
  assert.equal((await post('/contacts/import',{revision:repeatedPreview.revision,selected:[person.jid]})).body.imported,0);
  const intake=resolveIntake('synthetic-intake',{requested_pins_verbatim:['Unique Demo','Ambiguous Demo'],requested_client_labels_verbatim:{unresolved:['Unique Demo']}},[{jid:'unique@lid',name:'Unique Demo'},{jid:'one@lid',name:'Ambiguous Demo'},{jid:'two@lid',name:'Ambiguous Demo'}]);
  assert.equal(intake.resolved,1); assert.equal(intake.unresolved,2); assert.equal(intake.pins,1);
  const options={waPath:process.env.AB_ROLODEX_WA+'.unit',now:1800000000000};
  let preview=previewWhatsAppImport([person,person,{...person,jid:'group@g.us',isGroup:true}],accountKey(cfg.url),options);
  assert.equal(preview.contacts.length,1); assert.equal(preview.added,1); assert(preview.contacts[0].facts.every(f=>f.source&&f.observedAt&&f.confidence));
  assert.equal(importWhatsAppContacts(preview,options).imported,1);
  assert.equal(JSON.parse(readFileSync(options.waPath+'.previous.json')),null);
  const cache=readFileSync(options.waPath,'utf8');
  preview=previewWhatsAppImport([person],accountKey(cfg.url),{...options,now:1800000001000});
  assert.equal(preview.unchanged,1); assert.equal(importWhatsAppContacts(preview,options).imported,0); assert.equal(readFileSync(options.waPath,'utf8'),cache);
  preview=previewWhatsAppImport([{...person,name:'Avery Updated'}],accountKey(cfg.url),options);
  importWhatsAppContacts(preview,options,{selected:[person.jid],acceptConflicts:[person.jid]}); assert.equal(readFileSync(options.waPath+'.previous.json','utf8'),cache);
  // Selection is mandatory at the HTTP boundary and IDs must belong to this exact preview.
  assert.equal((await post('/contacts/import',{revision:repeatedPreview.revision})).status,400);
  assert.equal((await post('/contacts/import',{revision:repeatedPreview.revision,selected:['foreign@lid']})).status,400);
  // A metadata feed omitting a previously recorded phone must not erase it or churn repeated imports.
  const withoutPhone={...person}; delete withoutPhone.phone;
  const preservedOptions={waPath:process.env.AB_ROLODEX_WA+'.preserved',now:1800000000000};
  let preserved=previewWhatsAppImport([person],accountKey(cfg.url),preservedOptions);
  importWhatsAppContacts(preserved,preservedOptions);
  const preservedRaw=JSON.parse(readFileSync(preservedOptions.waPath));
  preservedRaw.contacts[0].labels=['Reviewed label'];
  preservedRaw.contacts[0].facts.push({field:'role',value:'Fixture operator',source:'fixture-explicit',observedAt:'2026-10-06',confidence:'source-record'});
  writeFileSync(preservedOptions.waPath,JSON.stringify(preservedRaw));
  preserved=previewWhatsAppImport([{...withoutPhone,messages:3}],accountKey(cfg.url),preservedOptions);
  importWhatsAppContacts(preserved,preservedOptions);
  const preservedResult=JSON.parse(readFileSync(preservedOptions.waPath)).contacts[0];
  assert(preservedResult.facts.some(f=>f.field==='phone')); assert(preservedResult.facts.some(f=>f.field==='role'));
  assert.deepEqual(preservedResult.labels,['Reviewed label']);
  assert.equal(previewWhatsAppImport([{...withoutPhone,messages:3}],accountKey(cfg.url),preservedOptions).unchanged,1);
  const reviewOptions={waPath:process.env.AB_ROLODEX_WA+'.review',now:1800000000000};
  const other={...person,jid:'other@lid',name:'Jordan Fixture'};
  preview=previewWhatsAppImport([person,other],accountKey(cfg.url),reviewOptions);
  let applied=importWhatsAppContacts(preview,reviewOptions,{selected:[person.jid]});
  assert.equal(applied.imported,1); assert.equal(JSON.parse(readFileSync(reviewOptions.waPath)).contacts.length,1);
  assert.equal(undoWhatsAppImport(applied.undoRevision,reviewOptions).restored,true);
  assert.equal(JSON.parse(readFileSync(reviewOptions.waPath)),null);
  preview=previewWhatsAppImport([person,other],accountKey(cfg.url),reviewOptions);
  applied=importWhatsAppContacts(preview,reviewOptions,{selected:[person.jid]});
  const untouchedCache=JSON.parse(readFileSync(reviewOptions.waPath));
  untouchedCache.contacts.push({chatId:'fixture-untouched@lid',displayName:'Untouched Fixture',customField:'kept exactly',labels:['old label']});
  untouchedCache.harvestedAt='2020-01-01T00:00:00.000Z';
  writeFileSync(reviewOptions.waPath,JSON.stringify(untouchedCache));
  const unchangedBytes=readFileSync(reviewOptions.waPath,'utf8');
  preview=previewWhatsAppImport([{...person,name:'Avery New Name'},other],accountKey(cfg.url),reviewOptions);
  assert.equal(preview.reviews.find(r=>r.chatId===person.jid).status,'conflict');
  assert.equal(importWhatsAppContacts(preview,reviewOptions,{selected:[person.jid]}).skipped,1);
  assert.equal(readFileSync(reviewOptions.waPath,'utf8'),unchangedBytes);
  applied=importWhatsAppContacts(preview,reviewOptions,{selected:[person.jid,other.jid],acceptConflicts:[person.jid]});
  assert.equal(applied.imported,2);
  const partialCache=JSON.parse(readFileSync(reviewOptions.waPath));
  assert.deepEqual(partialCache.contacts.find(c=>c.chatId==='fixture-untouched@lid'),untouchedCache.contacts.at(-1));
  assert.equal(partialCache.harvestedAt,'2020-01-01T00:00:00.000Z');
  writeFileSync(reviewOptions.waPath,readFileSync(reviewOptions.waPath,'utf8')+' ');
  assert.throws(()=>undoWhatsAppImport(applied.undoRevision,reviewOptions),/changed/);
  preview=previewWhatsAppImport([person,{...other,name:person.name}],accountKey(cfg.url),reviewOptions);
  assert(preview.reviews.every(r=>r.status==='unresolved'));
  assert.equal(importWhatsAppContacts(preview,reviewOptions,{selected:[person.jid,other.jid],acceptConflicts:[person.jid,other.jid]}).imported,0);
  preview=previewWhatsAppImport([person,{...person,name:'Contradictory fixture name'}],accountKey(cfg.url),reviewOptions);
  assert.equal(preview.reviews[0].status,'unresolved');
  assert.equal(importWhatsAppContacts(preview,reviewOptions,{selected:[person.jid],acceptConflicts:[person.jid]}).imported,0);
  writeFileSync(reviewOptions.waPath,'corrupt');
  assert.throws(()=>previewWhatsAppImport([person],accountKey(cfg.url),reviewOptions),/safely read/);
  console.log('PASS: selected subset, explicit conflict acceptance, ambiguous identities blocked, guarded undo, stale undo refusal, unreadable cache preservation');
  const home=path.join(process.env.AB_WHATSAPP_STATE,'fixture-home');
  const registry=path.join(home,'SISO_Workspace/SISO_Agency/clients'); mkdirSync(registry,{recursive:true});
  writeFileSync(path.join(registry,'CLIENTS.json'),JSON.stringify({clients:[],rolodex:{'Avery Fixture':{on_rolodex:true}}}));
  const people=list({home,wa:{contacts:[{chatId:'10000000001@s.whatsapp.net',displayName:'Avery Fixture',lastContacted:123},{chatId:'10000000002@s.whatsapp.net',displayName:'Avery Fixture',lastContacted:456}]}});
  assert.equal(people[0].identityConfidence,'unresolved'); assert.equal(people[0].lastContact,undefined);
  console.log('PASS: origin, explicit send, payload bounds, concurrent/replayed duplicates, durable unknown outcome, retryable rejection, read-receipt refusal, persistent pins/nested folders/bookmarks, stale revision, ambiguous identities, provenance and idempotent/reversible imports');
} finally { app.closeAllConnections(); gateway.closeAllConnections(); await Promise.all([new Promise(r=>app.close(r)),new Promise(r=>gateway.close(r))]); }
