import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,realpath,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {createServer} from 'node:http';
import {createWidgetReader} from '../src/widgets.ts';
import {widgetsRoute} from '../src/routes/widgets.route.ts';
import {widgetActionsRoute} from '../src/routes/widget-actions.route.ts';
import {dispatchRoute} from '../src/routes/registry.ts';
const temp=await realpath(await mkdtemp(path.join(os.tmpdir(),'ab-widgets-unit-'))),root=path.join(temp,'widgets');
const fixture={id:'needs',agent:'A0',title:'Review work',shape:'needs',updated:new Date().toISOString(),data:{items:[{id:'review',title:'Review the synthetic work',link:'javascript:alert(1)'}]},actions:[{kind:'seen'},{kind:'reply'},{kind:'voice'}]};
const previousAnswer=process.env.AB_CONSOLE_ANSWER_URL;let httpLines=0;const checks=[];const check=(id,value)=>{assert.ok(value,id);checks.push(id);};let server;
try{
 await mkdir(path.join(root,'A0'),{recursive:true});await writeFile(path.join(root,'A0/needs.json'),JSON.stringify(fixture));
 const reader=createWidgetReader(root);let sent=[];const routes=[widgetsRoute(reader),widgetActionsRoute(reader,async delivery=>{sent.push(delivery);await writeFile(path.join(temp,'A0.jsonl'),JSON.stringify(delivery.target.body)+'\n',{flag:'a'});})];
 server=createServer(async(req,res)=>{const url=new URL(req.url,'http://fixture');if(req.method==='POST'&&url.pathname==='/fixture-inbox'){const parts=[];for await(const part of req)parts.push(part);const body=JSON.parse(Buffer.concat(parts).toString());assert.equal(body.agent,'A0');assert.equal(body.card,'a0-board');await writeFile(path.join(temp,'A0.jsonl'),JSON.stringify(body)+'\n',{flag:'a'});httpLines++;res.writeHead(200,{'Content-Type':'application/json'});res.end('{"ok":true}');return;}if(!await dispatchRoute(routes,req,res,url.pathname,url)){res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
 const fetchJson=async(p,options)=>{const r=await fetch(base+p,options);return {status:r.status,body:await r.json()};};
 const w=(await fetchJson('/api/widgets/A0/needs')).body;check('bounded-owned-document-and-inert-links',w.id==='needs'&&!('link' in w.data.items[0]));
 await writeFile(path.join(root,'A0/bad.json'),'{torn');await writeFile(path.join(root,'A0/wrong.json'),JSON.stringify({...fixture,id:'wrong',agent:'Other'}));await writeFile(path.join(root,'A0/oversize.json'),'x'.repeat(262145));await writeFile(path.join(root,'A0/invalid.json'),JSON.stringify({...fixture,id:'invalid',data:{items:[{}]}}));
 const index=(await fetchJson('/api/widgets/A0')).body;check('malformed-mismatched-oversized-excluded',index.widgets.length===1&&index.excluded===4);
 check('encoded-traversal-refused',(await fetchJson('/api/widgets/%2e%2e%2fA0/needs')).status===400);check('encoded-detail-slash-refused',(await fetchJson('/api/widgets/A0/a%2fb')).status===400);
 check('missing-source-explicit',(await fetchJson('/api/widgets/Absent')).body.error==='Widget source unavailable');
 const post=body=>fetchJson('/api/widgets/A0/needs/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
 check('stale-action-no-send',(await post({kind:'seen',revision:'old'})).status===409&&sent.length===0);
 check('unsupported-action-no-send',(await post({kind:'delete',revision:w.revision})).status===422&&sent.length===0);
 check('empty-reply-no-send',(await post({kind:'reply',text:' ',revision:w.revision})).status===400&&sent.length===0);
 check('foreign-origin-no-send',(await fetchJson('/api/widgets/A0/needs/actions',{method:'POST',headers:{Origin:'https://elsewhere.invalid'},body:JSON.stringify({kind:'seen',revision:w.revision})})).status===403&&sent.length===0);
 check('seen-existing-transport-one-inbox-line',(await post({kind:'seen',revision:w.revision})).status===200&&sent.length===1&&(await readFile(path.join(temp,'A0.jsonl'),'utf8')).trim().split('\n').length===1&&sent[0].target.body.agent==='A0'&&sent[0].target.body.text==='re: notification widget:needs: Seen: Review work');
 process.env.AB_CONSOLE_ANSWER_URL=base+'/fixture-inbox';routes[1]=widgetActionsRoute(reader);check('default-console-http-delivery-to-fake-inbox',(await post({kind:'seen',revision:w.revision})).status===200&&httpLines===1&&(await readFile(path.join(temp,'A0.jsonl'),'utf8')).trim().split('\n').length===2);
 const announcement={...fixture,id:'announcements',shape:'announcements',title:'Announcements',data:{items:[{id:'7',title:'Synthetic announcement',body:'Ready',project:'Fixture',at:'2026-10-06T00:00:00Z',seen:false}]}};
 await writeFile(path.join(root,'A0/announcements.json'),JSON.stringify(announcement));
 const a=(await fetchJson('/api/widgets/A0/announcements')).body;
 const itemPost=body=>fetchJson('/api/widgets/A0/announcements/actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:a.revision,...body})});
 check('announcement-requires-current-item',(await itemPost({kind:'seen'})).status===422&&(await itemPost({kind:'seen',itemId:'unknown'})).status===422);
 check('announcement-stale-revision-refused',(await itemPost({kind:'seen',itemId:'7',revision:'old'})).status===409);
 check('ordinary-widget-rejects-item-protocol',(await post({kind:'seen',revision:w.revision,itemId:'7'})).status===422);
 check('announcement-seen-exact-existing-inbox-protocol',(await itemPost({kind:'seen',itemId:'7'})).status===200&&JSON.parse((await readFile(path.join(temp,'A0.jsonl'),'utf8')).trim().split('\n').at(-1)).text==='announcement 7: seen');
 check('announcement-reply-exact-existing-inbox-protocol',(await itemPost({kind:'reply',itemId:'7',text:'Looks ready'})).status===200&&JSON.parse((await readFile(path.join(temp,'A0.jsonl'),'utf8')).trim().split('\n').at(-1)).text==='announcement 7: Looks ready');
 await writeFile(path.join(root,'A0/announcements.json'),JSON.stringify({...announcement,data:{items:[...announcement.data.items,...announcement.data.items]}}));
 check('duplicate-announcement-identity-rejected',(await fetchJson('/api/widgets/A0/announcements')).status===404);
 const late=createWidgetReader(path.join(temp,'late'));let stop;const published=new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Late root publication was missed')),1500);late.subscribe('A0',async()=>{if((await late.index('A0')).widgets.length){clearTimeout(timer);resolve(true);}}).then(s=>{stop=s;});});await new Promise(r=>setTimeout(r,30));await mkdir(path.join(temp,'late/A0'),{recursive:true});await writeFile(path.join(temp,'late/A0/needs.json'),JSON.stringify(fixture));check('first-publication-after-subscription',await published);stop();
 console.log(JSON.stringify({passed:checks.length,checks}));
 await writeFile(path.resolve(import.meta.dirname,'../../../.agents/scratchpads/landing-20261006/widget-mechanism-unit.json'),JSON.stringify({passed:checks.length,checks},null,2)+'\n');
}finally{if(previousAnswer===undefined)delete process.env.AB_CONSOLE_ANSWER_URL;else process.env.AB_CONSOLE_ANSWER_URL=previousAnswer;await new Promise(r=>server?server.close(r):r());await rm(temp,{recursive:true,force:true});}
