import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,realpath,rename,rm} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';
import {suitePort,webkit} from './suite-runtime.mjs';
import {createServer} from '../../../apps/web/node_modules/vite/dist/node/index.js';
import react from '../../../apps/web/node_modules/@vitejs/plugin-react/dist/index.js';
import tailwindcss from '../../../apps/web/node_modules/@tailwindcss/vite/dist/index.mjs';
import {createWidgetReader} from '../src/widgets.ts';import {widgetsRoute} from '../src/routes/widgets.route.ts';import {widgetActionsRoute} from '../src/routes/widget-actions.route.ts';import {dispatchRoute} from '../src/routes/registry.ts';
const repo=path.resolve(import.meta.dirname,'../../..'),web=path.join(repo,'apps/web');
// --out retains evidence in a caller-owned directory; each default run gets fresh output.
const outFlag=process.argv.indexOf('--out');
if(outFlag!==-1&&(!process.argv[outFlag+1]||process.argv[outFlag+1].startsWith('--')))throw Error('--out requires an output directory');
const out=outFlag===-1?await mkdtemp(path.join(os.tmpdir(),'.siso-ephemeral-widgets-ui-output-')):path.resolve(process.argv[outFlag+1]);
await mkdir(out,{recursive:true});console.log(`Evidence: ${out}`);
const temp=await realpath(await mkdtemp(path.join(os.tmpdir(),'ab-widgets-ui-'))),root=path.join(temp,'widgets'),inbox=path.join(temp,'A0.jsonl');
const files=['services/node/src/widgets.ts','services/node/src/routes/widgets.route.ts','services/node/src/routes/widget-actions.route.ts','apps/web/src/components/widgets/AgentWidgets.tsx','apps/web/src/components/widgets/AgentWidgets.css'];
const hashes=async()=>Object.fromEntries(await Promise.all(files.map(async f=>[f,createHash('sha256').update(await readFile(path.join(repo,f))).digest('hex')])));const before=await hashes();
let server,browser,page,failDelivery=false;const checks=[],errors=[],unexpected=[],requests=[];const record=(id,detail={})=>{checks.push({id,status:'PASS',...detail});console.log(JSON.stringify(checks.at(-1)));};
const base={agent:'A0',updated:new Date().toISOString(),actions:[]};const needs={...base,id:'needs',title:'Needs review',shape:'needs',data:{items:[{id:'one',title:'Review the synthetic release',detail:'Confirm the rendered result',minutes:2,link:'https://untrusted.invalid/'}]},actions:[{kind:'seen'},{kind:'reply'},{kind:'voice'}]};
const fixtures=[needs,{...base,id:'list',title:'Goals',shape:'list',data:{rows:Array.from({length:12},(_,i)=>({meta:'Today',title:`Synthetic goal ${i+1}`}))}},{...base,id:'progress',title:'Plan progress',shape:'progress',data:{checked:1,total:2,counts:{checked:1,building:1},items:[{title:'Synthetic build',status:'building'},{title:'Synthetic checked',status:'checked'}]}},{...base,id:'team',title:'Team',shape:'team',data:{members:[{name:'Synthetic owner',state:'idle',model:'Fixture',task:'No live task'}]}},{...base,id:'systems',title:'Machines',shape:'systems',data:{source:'servers'}},{...base,id:'announcements',title:'Announcements',shape:'announcements',data:{items:[{id:'notice',title:'Synthetic announcement',body:'Review complete',project:'Fixture project',at:'2026-10-06T00:00:00Z',needs:'Review',seen:false}]},actions:[{kind:'seen'},{kind:'reply'},{kind:'voice'}]},{...base,id:'unknown',title:'Safe fallback',shape:'future',data:{message:'<script>window.injected=true</script>'}}];
try{
 await mkdir(path.join(root,'A0'),{recursive:true});for(const w of fixtures)await writeFile(path.join(root,'A0',w.id+'.json'),JSON.stringify(w));
 const reader=createWidgetReader(root),routes=[widgetsRoute(reader),widgetActionsRoute(reader,async d=>{if(failDelivery)throw Error('Synthetic inbox unavailable');assert.equal(d.target.kind,'console');await writeFile(inbox,JSON.stringify(d.target.body)+'\n',{flag:'a'});})];
 const port=await suitePort();
 server=await createServer({configFile:false,root:web,plugins:[react(),tailwindcss(),{name:'sealed-widgets',configureServer(v){v.middlewares.use(async(req,res,next)=>{const url=new URL(req.url,'http://fixture');if(!url.pathname.startsWith('/api/'))return next();requests.push(`${req.method} ${url.pathname}`);if(await dispatchRoute(routes,req,res,url.pathname,url))return;if(req.method==='GET'&&url.pathname==='/api/servers'){res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({servers:[{name:'Synthetic machine',role:'Fixture',health:{level:'ok',cpus:4,load:[1],memTotalGb:16,memAvailGb:8,diskFreeGb:40,why:[]}}]}));return;}unexpected.push(`${req.method} ${url.pathname}`);res.writeHead(503);res.end('{}');});}}],cacheDir:path.join(temp,'vite'),resolve:{dedupe:['react','react-dom']},optimizeDeps:{entries:['preview/agent-widgets.html']},server:{host:'127.0.0.1',port,strictPort:true,hmr:{host:'127.0.0.1',clientPort:port},fs:{allow:[repo]}}});await server.listen();const origin=`http://127.0.0.1:${port}`;
 browser=await webkit.launch({headless:true});
 for(const width of [1440,390]){
  page=await browser.newPage({viewport:{width,height:900},reducedMotion:'reduce'});page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',r=>{if(new URL(r.request().url()).origin!==origin){unexpected.push('external');return r.abort();}return r.continue();});await page.routeWebSocket('**/*',ws=>{const u=new URL(ws.url());if(u.host===new URL(origin).host&&u.pathname==='/')ws.connectToServer();else{unexpected.push('socket');ws.close();}});
  await writeFile(path.join(root,'A0/needs.json'),JSON.stringify(needs));await page.goto(origin+'/preview/agent-widgets.html');await page.getByRole('button',{name:'Open Needs review',exact:true}).waitFor();assert.equal(await page.locator('nav button').count(),7);record(`index-seven-shapes-${width}`);
  await page.getByRole('button',{name:'Open Needs review',exact:true}).click();await page.getByText('Review the synthetic release',{exact:true}).waitFor();assert.equal(await page.locator('[data-widget-id]').count(),1);assert.equal(await page.locator('a[href]').count(),0);record(`single-widget-safe-needs-${width}`);
  await page.screenshot({path:path.join(out,`widgets-needs-before-${width}.png`),fullPage:true});
  const changed={...needs,updated:new Date().toISOString(),data:{items:[{id:'one',title:'Updated synthetic release is ready',detail:'The file changed without reload',minutes:1}]}};
  await page.getByLabel('Reply',{exact:true}).fill('Draft survives file updates');
  const start=Date.now();await writeFile(path.join(root,'A0/needs.next'),JSON.stringify(changed));await rename(path.join(root,'A0/needs.next'),path.join(root,'A0/needs.json'));await page.getByText('Updated synthetic release is ready',{exact:true}).waitFor({timeout:2000});const elapsedMs=Date.now()-start;assert.ok(elapsedMs<2000);record(`file-to-open-panel-under-two-seconds-${width}`,{elapsedMs});assert.equal(await page.getByLabel('Reply',{exact:true}).inputValue(),'Draft survives file updates');record(`draft-survives-file-update-${width}`);
  const oldLines=await readFile(inbox,'utf8').then(s=>s.trim().split('\n').length).catch(()=>0);await page.getByRole('button',{name:'Seen',exact:true}).click();await page.getByRole('button',{name:'Seen recorded',exact:true}).waitFor();const lines=(await readFile(inbox,'utf8')).trim().split('\n').map(JSON.parse);assert.equal(lines.length,oldLines+1);assert.match(lines.at(-1).text,/Seen: Needs review/);record(`seen-one-synthetic-inbox-record-${width}`);
  await page.getByLabel('Reply',{exact:true}).fill('Synthetic reply only');await page.getByRole('button',{name:'Send reply',exact:true}).click();await page.getByText('Reply delivered.',{exact:true}).waitFor();await page.getByRole('button',{name:'Voice reply',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.agent-widgets__actions button:last-of-type')?.disabled);const messages=(await readFile(inbox,'utf8')).trim().split('\n').map(JSON.parse);assert.match(messages.at(-1).text,/Voice: Synthetic voice transcript/);record(`reply-and-voice-existing-delivery-${width}`);
  await page.getByRole('button',{name:'Seen recorded',exact:true}).waitFor();failDelivery=true;await page.getByLabel('Reply',{exact:true}).fill('Retained failed reply');await page.getByRole('button',{name:'Send reply',exact:true}).click();await page.getByRole('alert').filter({hasText:'Action not delivered'}).waitFor();assert.equal(await page.getByLabel('Reply',{exact:true}).inputValue(),'Retained failed reply');failDelivery=false;record(`failed-delivery-retains-draft-${width}`);await page.getByRole('button',{name:'Send reply',exact:true}).click();await page.getByRole('alert').waitFor({state:'detached'});await page.waitForFunction(()=>document.querySelector('textarea')?.value==='');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,`widgets-needs-after-${width}.png`),fullPage:true});record(`no-horizontal-overflow-${width}`);
  await page.getByRole('button',{name:'All widgets',exact:true}).click();await page.getByRole('button',{name:'Open Announcements',exact:true}).click();
  await page.getByText('Fixture project · 2026-10-06T00:00:00Z',{exact:true}).waitFor();
  await page.getByLabel('Reply to announcement notice',{exact:true}).fill('Synthetic item reply');failDelivery=true;
  await page.getByRole('button',{name:'Send reply to announcement notice',exact:true}).click();await page.getByRole('alert').filter({hasText:'Action not delivered'}).waitFor();
  assert.equal(await page.getByLabel('Reply to announcement notice',{exact:true}).inputValue(),'Synthetic item reply');failDelivery=false;
  await page.getByRole('button',{name:'Send reply to announcement notice',exact:true}).click();await page.getByText('Reply delivered.',{exact:true}).waitFor();
  assert.equal(JSON.parse((await readFile(inbox,'utf8')).trim().split('\n').at(-1)).text,'announcement notice: Synthetic item reply');
  await page.screenshot({path:path.join(out,`widgets-announcements-before-seen-${width}.png`),fullPage:true});
  await page.getByRole('button',{name:'Mark announcement notice seen',exact:true}).click();await page.getByText('Fixture project · 2026-10-06T00:00:00Z · Seen',{exact:true}).waitFor();
  assert.equal(JSON.parse((await readFile(inbox,'utf8')).trim().split('\n').at(-1)).text,'announcement notice: seen');
  assert.equal(await page.getByRole('button',{name:'Mark announcement notice seen',exact:true}).count(),0);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,`widgets-announcements-after-seen-${width}.png`),fullPage:true});record(`announcement-item-protocol-and-failed-draft-${width}`);
  for(const [title,selector]of [['Goals','.widget-list-shape'],['Plan progress','.widget-progress'],['Team','.widget-team'],['Machines','.widget-systems'],['Announcements','.siso-widget'],['Safe fallback','.widget-unknown']]){await page.getByRole('button',{name:'All widgets',exact:true}).click();await page.getByRole('button',{name:`Open ${title}`,exact:true}).click();await page.locator(selector).waitFor();assert.equal(await page.locator('[data-widget-id]').count(),1);if(title==='Goals'){assert.equal(await page.locator('.widget-list-shape__rows li').count(),12);record(`complete-list-all-twelve-rows-${width}`);}if(title==='Plan progress'){await page.getByText('1 of 2 checked',{exact:true}).waitFor();record(`checked-progress-not-double-counted-${width}`);}}
  assert.equal(await page.evaluate(()=>window.injected),undefined);record(`shared-renderers-and-inert-unknown-${width}`);await page.screenshot({path:path.join(out,`widgets-fallback-${width}.png`),fullPage:true});const from=requests.length;await page.goto(origin+'/preview/agent-widgets.html?widget=needs');await page.getByText('Updated synthetic release is ready',{exact:true}).waitFor();assert.equal(await page.locator('[data-widget-id]').count(),1);assert.equal(await page.locator('nav').count(),0);assert.ok(requests.slice(from).filter(r=>/^GET \/api\/widgets\/A0\/(?!events$)/.test(r)).every(r=>r==='GET /api/widgets/A0/needs'));record(`controlled-single-widget-entry-${width}`);await page.close();
 }
 assert.deepEqual(errors,[]);assert.deepEqual(unexpected,[]);assert.deepEqual(await hashes(),before);record('sealed-transport-source-stability',{errors:0,unexpected:0});
 await writeFile(path.join(out,'widget-mechanism-ui.json'),JSON.stringify({at:new Date().toISOString(),checks,passed:checks.length,errors,unexpected,requests,hashes:before,browserClosed:true,serverClosed:true,fixtureRemoved:true},null,2)+'\n');
}catch(error){console.error(JSON.stringify({error:String(error),errors,unexpected,body:page&&!page.isClosed()?await page.locator('body').innerText():null}));throw error;}finally{await browser?.close();await server?.close();await rm(temp,{recursive:true,force:true});}
