// Synthetic repositories and owned receipts only. Never starts providers or ships/deploys.
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,symlinkSync,renameSync,realpathSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {readWriterDossier,checkLandingWriter,compareWriterJobs} from '../src/writer-gates.ts';
import {acceptLaunch,withLaunch,getWorkspace,receiptFile} from '../src/worktrees.ts';
import {validateWorkspaceReceipt} from '../../host/src/worktree-contract.ts';

const scratch=realpathSync(mkdtempSync(path.join(tmpdir(),'.siso-ephemeral-writer-gates.')));
const repo=path.join(scratch,'repo');mkdirSync(repo);
process.env.AB_WORKSPACES_DIR=path.join(scratch,'receipts');
process.env.AB_WORKTREE_ROOT=path.join(scratch,'worktrees');
const g=(cwd,...args)=>execFileSync('git',['-C',cwd,...args],{encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
const put=(cwd,file,text)=>{mkdirSync(path.dirname(path.join(cwd,file)),{recursive:true});writeFileSync(path.join(cwd,file),text);};
const json=(cwd,file,value)=>put(cwd,file,JSON.stringify(value));
const sha=v=>createHash('sha256').update(v).digest('hex');
const commit=(cwd,msg)=>{g(cwd,'add','.');g(cwd,'commit','-qm',msg);return g(cwd,'rev-parse','HEAD');};
const head=cwd=>g(cwd,'rev-parse','HEAD');
let count=0;const pass=label=>console.log(`ok ${++count} - ${label}`);
g(repo,'init','-q','-b','main');g(repo,'config','user.name','Writer fixture');g(repo,'config','user.email','fixture@example.invalid');
put(repo,'component.ts','export const value = 1;\n');
json(repo,'.agents/workspace.json',{version:1,fetch:false,submodules:'none',setup:[]});
json(repo,'ui-hub/components.json',{components:[{id:'fixture'}]});
const roles=['files','traps','reasoning','feedback'];
for(const role of roles)put(repo,`ui-hub/fixture/${role}.md`,`# ${role}\n\nThis fixture component owns component.ts; preserve its exported value and verify every edited revision.\n`);
const codeRevision=commit(repo,'Fixture source');
const dossier=(cwd,sourceRevision)=>({version:1,sourceRevision,files:[{path:'component.ts',sha256:sha(readFileSync(path.join(cwd,'component.ts')))}],context:roles.map(role=>({role,path:`ui-hub/fixture/${role}.md`,sha256:sha(readFileSync(path.join(cwd,`ui-hub/fixture/${role}.md`)))}))});
let currentDossier=dossier(repo,codeRevision);
json(repo,'ui-hub/fixture/component.json',{id:'fixture',writerDossier:currentDossier});commit(repo,'Fixture dossier');
const initial=await readWriterDossier(repo,'fixture');assert.equal(initial.sourceRevision,head(repo));assert.equal(initial.dossierDigest.length,64);
await assert.rejects(()=>readWriterDossier(repo,undefined),/explicit catalog surface/);
await assert.rejects(()=>readWriterDossier(repo,'missing'),/absent/);pass('clean committed dossier, explicit surface and catalog membership');
put(repo,'component.ts','export const value = 2;\n');await assert.rejects(()=>readWriterDossier(repo,'fixture'),/dirty/);assert.equal(readFileSync(path.join(repo,'component.ts'),'utf8'),'export const value = 2;\n');put(repo,'component.ts','export const value = 1;\n');
const changed=structuredClone(currentDossier);changed.context[0].sha256='0'.repeat(64);json(repo,'ui-hub/fixture/component.json',{id:'fixture',writerDossier:changed});commit(repo,'Stale hash');await assert.rejects(()=>readWriterDossier(repo,'fixture'),/stale/);
json(repo,'ui-hub/fixture/component.json',{id:'fixture',writerDossier:currentDossier});commit(repo,'Restore fixture hash');pass('dirty source preserved and committed stale hashes rejected');
for(const invalid of ['../outside','.env.local']){
 const bad=structuredClone(currentDossier);bad.files[0].path=invalid;json(repo,'ui-hub/fixture/component.json',{id:'fixture',writerDossier:bad});commit(repo,'Invalid evidence path');await assert.rejects(()=>readWriterDossier(repo,'fixture'),/invalid file binding/i);
}
json(repo,'ui-hub/fixture/component.json',{id:'fixture',writerDossier:currentDossier});commit(repo,'Restore evidence paths');
renameSync(path.join(repo,'ui-hub/fixture/files.md'),path.join(scratch,'files.md'));symlinkSync(path.join(scratch,'files.md'),path.join(repo,'ui-hub/fixture/files.md'));commit(repo,'Fixture link');await assert.rejects(()=>readWriterDossier(repo,'fixture'),/symbolic links/);
renameSync(path.join(repo,'ui-hub/fixture/files.md'),path.join(scratch,'retained-link'));renameSync(path.join(scratch,'files.md'),path.join(repo,'ui-hub/fixture/files.md'));commit(repo,'Restore regular context');pass('path traversal, private evidence and symbolic links refused');
const before=await readWriterDossier(repo,'fixture');
const input=(id,writer=before,workspace={type:'isolated'})=>({launchId:id,name:`WRITER-${id}`,repo,harness:'codex',model:'fixture-no-provider',writer,workspace});
const stale=await acceptLaunch(input('stale'));
put(repo,'component.ts','export const value = 3;\n');await withLaunch(stale,async()=>assert.fail('provider callback must not run'));assert.equal(getWorkspace(stale.workspaceId).phase,'failed');assert.equal(readFileSync(path.join(repo,'component.ts'),'utf8'),'export const value = 3;\n');put(repo,'component.ts','export const value = 1;\n');
const shared=await acceptLaunch(input('shared',before,{type:'shared',reason:'fixture'}));await withLaunch(shared,async()=>assert.fail('shared writer cannot launch'));assert.equal(getWorkspace(shared.workspaceId).phase,'failed');pass('preparation rechecks dossier and refuses shared writers before any provider');
const accepted=await acceptLaunch(input('owned'));await withLaunch(accepted,async()=>{});const receipt=getWorkspace(accepted.workspaceId),source=receipt.worktreePath;assert.equal(receipt.phase,'ready');assert.equal(receipt.baseSha,before.sourceRevision);assert.equal(validateWorkspaceReceipt(receiptFile(receipt.workspaceId),source).workspaceId,receipt.workspaceId);pass('existing allocator creates revision-pinned isolated workspace and usable receipt');
const ref=`refs/heads/${receipt.branch}`,target=head(repo);
put(source,'component.ts','export const value = 4;\n');const codeAfter=commit(source,'Writer change');
put(source,'ui-hub/fixture/feedback.md','# Feedback\n\nThe fixture value changed from one to four; the focused check must verify the current export before landing.\n');
currentDossier=dossier(source,codeAfter);json(source,'ui-hub/fixture/component.json',{id:'fixture',writerDossier:currentDossier});commit(source,'Writer dossier update');
const after=await readWriterDossier(source,'fixture');
const declaration={version:1,workspaceId:receipt.workspaceId,surface:'fixture',targetRevision:target,dossierBefore:before.dossierDigest,dossierAfter:after.dossierDigest};
json(source,'.agents/ship.json',{tests:'node -e "process.exit(0)"',writer:declaration});const delivered=commit(source,'Delivery declaration');
const gate=await checkLandingWriter(repo,ref,delivered,target,receiptFile);assert.equal(gate.phase,'ready-for-checks');assert.equal(gate.tests,'node -e "process.exit(0)"');assert.equal('checked' in gate,false);pass('clean rebased owned writer with updated context reaches checks, without claiming they passed');
await assert.rejects(()=>checkLandingWriter(repo,ref,codeAfter,target,receiptFile),/branch moved/);
put(source,'component.ts','Uncommitted author work\n');await assert.rejects(()=>checkLandingWriter(repo,ref,delivered,target,receiptFile),/dirty/);assert.equal(readFileSync(path.join(source,'component.ts'),'utf8'),'Uncommitted author work\n');put(source,'component.ts','export const value = 4;\n');
const oldReceipt=readFileSync(receiptFile(receipt.workspaceId));const invalidReceipt=JSON.parse(oldReceipt);invalidReceipt.baseSha='0'.repeat(40);writeFileSync(receiptFile(receipt.workspaceId),JSON.stringify(invalidReceipt));await assert.rejects(()=>checkLandingWriter(repo,ref,delivered,target,receiptFile),/binding changed/);writeFileSync(receiptFile(receipt.workspaceId),oldReceipt);
await assert.rejects(()=>checkLandingWriter(repo,ref,delivered,target,()=>path.join(scratch,'absent-receipt')),/missing|ENOENT/);pass('moved branch, dirty author work, stale workspace binding and absent receipt rejected');
// Exercise the actual queue helper and its dirty-checkout preservation path without calling ship/run.
const queue=path.resolve(import.meta.dirname,'../../../tools/ab-queue');
const python=`import runpy, os, json\nm=runpy.run_path(${JSON.stringify(queue)})\ng=m['writer_gate'](${JSON.stringify(ref)},${JSON.stringify(delivered)},${JSON.stringify(target)})\nassert g['phase']=='ready-for-checks'\np=os.path.join(os.environ['AB_MERGE_WORKTREE'],'keep.txt')\nwith open(p,'w') as f:f.write('owned dirty content')\ntry:m['merge_onto'](${JSON.stringify(target)},[])\nexcept RuntimeError as e:assert 'dirty' in str(e)\nelse:raise AssertionError('dirty landing accepted')\nassert open(p).read()=='owned dirty content'\nprint('queue gate and dirty preservation passed')\n`;
assert.match(execFileSync('python3',['-c',python],{encoding:'utf8',env:{...process.env,AB_REPO:repo,AB_MERGE_WORKTREE:repo,AB_QUEUE_STATE:path.join(scratch,'queue')}}),/passed/);renameSync(path.join(repo,'keep.txt'),path.join(scratch,'keep.txt'));pass('real queue writer gate and dirty landing checkout preserve owner content');
put(repo,'main-only.txt','New target revision\n');const newTarget=commit(repo,'Target advanced');await assert.rejects(()=>checkLandingWriter(repo,ref,delivered,newTarget,receiptFile),/rebased/);pass('target advance requires author rebase and renewed declaration');
json(source,'.agents/ship.json',{tests:'',writer:declaration});const noChecks=commit(source,'Missing checks');await assert.rejects(()=>checkLandingWriter(repo,ref,noChecks,target,receiptFile),/declare the checks/);
json(source,'.agents/ship.json',{tests:'node -e "process.exit(0)"',writer:declaration});put(source,'outside.ts','export const unrelated = true;\n');const outside=commit(source,'Out of scope');await assert.rejects(()=>checkLandingWriter(repo,ref,outside,target,receiptFile),/outside its bound/);pass('missing checks and code outside the bound inventory rejected');
renameSync(path.join(source,'outside.ts'),path.join(scratch,'outside.ts'));
put(source,'ui-hub/fixture/feedback.md',g(source,'show',`${target}:ui-hub/fixture/feedback.md`)+'\n');
json(source,'ui-hub/fixture/component.json',{id:'fixture',writerDossier:dossier(source,codeAfter)});commit(source,'Remove completion context update');
const withoutContext=await readWriterDossier(source,'fixture');json(source,'.agents/ship.json',{tests:'node -e "process.exit(0)"',writer:{...declaration,dossierAfter:withoutContext.dossierDigest}});const noContext=commit(source,'Declaration without context update');
await assert.rejects(()=>checkLandingWriter(repo,ref,noContext,target,receiptFile),/updated component context/);pass('code and hash updates alone cannot replace completion context');
json(source,'.agents/ship.json',{tests:'true'});const stripped=commit(source,'Removed writer declaration');
await assert.rejects(()=>checkLandingWriter(repo,ref,stripped,target,receiptFile),/writer binding is missing/);
pass('removing the writer declaration cannot downgrade a component-owned receipt');
const generalInput=input('general');delete generalInput.writer;
const generalAccepted=await acceptLaunch(generalInput);await withLaunch(generalAccepted,async()=>{});
const general=getWorkspace(generalAccepted.workspaceId),generalSource=general.worktreePath,generalRef=`refs/heads/${general.branch}`;
assert.equal(general.phase,'ready');json(generalSource,'.agents/ship.json',{tests:'true'});put(generalSource,'general-change.txt','A general release without component ownership.\n');const generalRevision=commit(generalSource,'General release');
const generalGate=await checkLandingWriter(repo,generalRef,generalRevision,newTarget,receiptFile);assert.equal(generalGate.kind,'general');assert.equal(generalGate.phase,'ready-for-checks');
json(generalSource,'.agents/ship.json',{tests:'true',writer:null});const malformed=commit(generalSource,'Malformed explicit writer');await assert.rejects(()=>checkLandingWriter(repo,generalRef,malformed,newTarget,receiptFile),/writer binding is missing/);
await assert.rejects(()=>acceptLaunch({...input('invalid'),writer:null}),/Invalid explicit writer/);
pass('general managed launches and releases remain valid; explicit malformed writer evidence fails closed');


const measured=(runId,mode)=>({runId,mode,sessionId:`session-${mode}`,resumedFrom:mode==='saved'?'old-session':null,taskId:'t-fixture',jobDigest:'1'.repeat(64),baseRevision:'2'.repeat(40),dossierDigest:'3'.repeat(64),sourceRevision:mode==='saved'?'4'.repeat(40):'5'.repeat(40),commandsBeforeFirstEdit:mode==='saved'?2:5,totalCommands:10,checks:[{sourceRevision:mode==='saved'?'4'.repeat(40):'5'.repeat(40),command:'fixture-check',exitCode:0}],shots:[{sourceRevision:mode==='saved'?'4'.repeat(40):'5'.repeat(40),sha256:'6'.repeat(64),viewport:{width:1440,height:900}}],measurementDigest:'7'.repeat(64)});
const saved=measured('saved-run','saved'),fresh=measured('fresh-run','fresh');
const compare=(a=saved,b=fresh)=>compareWriterJobs('saved-run','fresh-run',async id=>id==='saved-run'?a:b);
const result=await compare();assert.equal(result.commandsBeforeFirstEditDelta,3);assert.equal(result.visualVerdict,'unreviewed');assert.deepEqual(result.checks,{saved:true,fresh:true});
await assert.rejects(()=>compare(null),/missing or stale/);
for(const patch of [{baseRevision:'9'.repeat(40)},{jobDigest:'9'.repeat(64)},{dossierDigest:'9'.repeat(64)},{sessionId:saved.sessionId},{resumedFrom:'old-session'}])await assert.rejects(()=>compare(saved,{...fresh,...patch}),/same task, input, base and dossier/);
for(const patch of [{checks:[{...fresh.checks[0],sourceRevision:saved.sourceRevision}]},{shots:[]},{commandsBeforeFirstEdit:11},{measurementDigest:''}])await assert.rejects(()=>compare(saved,{...fresh,...patch}),/missing or stale/);
await assert.rejects(()=>compare(saved,{...fresh,checks:[{...fresh.checks[0],command:'different-check'}]}),/do not match/);
assert.equal((await compare(saved,{...fresh,checks:[{...fresh.checks[0],exitCode:1}]})).checks.fresh,false);pass('paired measured jobs bind baseline, dossier, sessions, checks and shots; visual verdict stays unreviewed');
// Existing allocator regression cases use committed dossier fixtures and mocked provider adapters.
execFileSync(process.execPath,['--experimental-strip-types','--no-warnings',path.join(import.meta.dirname,'task-actions.mjs')],{stdio:'inherit',env:process.env});
pass('existing task-allocation focused regression suite');
console.log(JSON.stringify({ok:true,groups:count,fixture:scratch,liveLaunches:0,experiment:'synthetic-only'}));
