import assert from 'node:assert/strict';
import {FlightLedger,deliveryPairs,pipelineMedian,runningResearch,verifiedDeliveries} from './delight.ts';
import {CodexTransitions} from './codex-transitions.ts';
const now=Date.parse('2026-10-06T08:00:00Z'),sha='a'.repeat(40),url=side=>`/api/releases/${sha}/evidence/mock/${side}`;
const r={id:'receipt',taskId:'task',title:'Delivered fixture',agentKey:'zero',session:'s1',prompt:{id:'p1',source:'prompt-ledger',at:new Date(now-120_000).toISOString()},live:{id:'l1',source:'live-ledger',at:new Date(now-60_000).toISOString(),revision:sha,verified:true},evidence:{state:'available',pairs:[{id:'mock',title:'Mock',before:url('before'),after:url('after'),beforeSha:'b'.repeat(40),afterSha:sha}]}};
assert.equal(verifiedDeliveries([r,r],'zero','s1',now).length,1);
for(const bad of [{...r,session:'s2'},{...r,agentKey:'another'},{...r,live:{...r.live,verified:false}},{...r,live:{...r.live,at:new Date(now+1).toISOString()}}])assert.equal(verifiedDeliveries([bad],'zero','s1',now).length,0);
assert.equal(deliveryPairs(r).length,1);
assert.equal(deliveryPairs({...r,evidence:{state:'available',pairs:[{...r.evidence.pairs[0],afterSha:'c'.repeat(40)}]}}).length,0);
assert.equal(deliveryPairs({...r,evidence:{state:'available',pairs:[{...r.evidence.pairs[0],after:'https://example.test/fake.png'}]}}).length,0);
assert.equal(deliveryPairs({...r,evidence:{state:'available',pairs:[{...r.evidence.pairs[0],after:r.evidence.pairs[0].after.replace(sha,'c'.repeat(40))}]}}).length,0);
assert.equal(pipelineMedian([r,r,{...r,id:'r2',taskId:'t2',prompt:{...r.prompt,at:new Date(now-240_000).toISOString()}}],'zero',now).median,120_000);
assert.equal(pipelineMedian([{...r,prompt:{...r.prompt,at:'unknown'}}],'zero',now).median,null);
assert.equal(pipelineMedian([{...r,prompt:{...r.prompt,at:r.live.at}}],'zero',now).median,null);
const fleet={name:'research',finished:null,jobs:[{status:'running'}],then:null};
const research={fleets:{at:now,data:[fleet,{...fleet,name:'done',finished:'date'}],error:null}};
assert.equal(runningResearch(research,null,now).fleets.length,1);
assert.equal(runningResearch(research,'failed',now).fleets.length,0);
assert.equal(runningResearch(research,null,now+30_001).unavailable,true);
assert.equal(runningResearch({...research,fleets:{...research.fleets,at:now+1}},null,now).unavailable,true);
const l=new FlightLedger();l.baseline(['old','finished'],['old']);assert.equal(l.claim('old','spawn'),false);l.returned('finished');assert.equal(l.claim('finished','return'),false);l.returned('old');assert.equal(l.claim('old','return'),true);l.returned('old');assert.equal(l.claim('old','return'),false);l.spawn('new');assert.equal(l.claim('new','spawn'),true);l.spawn('new');assert.equal(l.claim('new','spawn'),false);
l.spawn('expired');assert.equal(l.claim('expired','spawn',Date.now()+2001),false);l.spawn('expired');assert.equal(l.claim('expired','spawn'),false);
l.returned('unknown');assert.equal(l.claim('unknown','return'),false);
const c=new CodexTransitions(),ledger=new FlightLedger(),row={id:'run:one',start:new Date(now).toISOString(),running:true,status:'running',end:null};
c.observe([],ledger,now);c.observe([row],ledger,now+1);const key=`${row.id}:${row.start}`;assert.equal(ledger.claim(key,'spawn'),true);c.observe([row],ledger,now+2);assert.equal(ledger.claim(key,'spawn'),false);c.observe([{...row,running:false,status:'done',end:new Date(now+3).toISOString()}],ledger,now+3);assert.equal(ledger.claim(key,'return'),true);
c.reset();ledger.reset();c.observe([row],ledger,now+4);assert.equal(ledger.claim(key,'spawn'),false);c.observe([],ledger,now+5);assert.equal(ledger.claim(key,'return'),false);
c.observe([{...row,id:'historical',start:new Date(now-10000).toISOString()}],ledger,now+6);assert.equal(ledger.claim(`historical:${new Date(now-10000).toISOString()}`,'spawn'),false);
console.log('PASS: delivery identity, provenance, revision, median; research freshness; current-session lifecycle and replay prevention');
