import assert from 'node:assert/strict';
import {providerUsage,providerTone,resetDescription} from './provider-usage.ts';
const now=Date.parse('2026-10-06T12:00:00Z');
const window=(usedPct,resetsAt=now+3600000)=>({usedPct,resetsAt,expired:false});
const claude={id:'claude:example',kind:'claude',name:'Example',folder:'claude-example',person:{label:'Example account',email:'example@invalid.test',mine:true},limits:{at:now,source:'fixture usage cache',fiveHour:window(22),weekly:window(75)}};
const codex={id:'codex',kind:'codex',name:'Codex (fixture plan)',limits:{at:now,source:'fixture token_count event',fiveHour:window(92),weekly:window(15)}};
const view=(accounts,extra={},error=null,at=now)=>providerUsage({accounts,...extra},error,at);
let result=view([claude,codex]);assert.deepEqual(result.map(p=>[p.label,p.pct,p.state]),[['Claude',75,'fresh'],['Codex',92,'fresh']]);assert.equal(result[0].accounts[0].label,'Example account');assert.equal(result[1].accounts[0].label,null,'plan/profile is not an account name');
assert.equal(view([claude,{...claude,id:'other',person:{label:'Do not include',mine:false},limits:{...claude.limits,fiveHour:window(99)}}])[0].accounts.length,1);
assert.equal(view([claude,{...claude,limits:{...claude.limits,at:now-1,fiveHour:window(99)}}])[0].pct,75,'duplicate account does not add capacity');
assert.equal(view([{...claude,limits:{...claude.limits,at:now-300001}}])[0].state,'stale');assert.equal(view([claude],{cached:true})[0].state,'stale');assert.equal(view([claude],{},'HTTP 503')[0].state,'stale');
assert.equal(view([{...claude,limits:{...claude.limits,at:now+1}}])[0].state,'stale');assert.equal(view([{...claude,limits:{...claude.limits,at:null}}])[0].state,'stale');
result=view([{...claude,limits:{...claude.limits,fiveHour:window(22,now-1)}}]);assert.equal(result[0].state,'stale');assert.equal(result[0].accounts[0].windows[0].pct,22,'reset crossing does not invent zero');
result=view([{...claude,limits:{...claude.limits,fiveHour:window(-1),weekly:window(101)}}]);assert.equal(result[0].pct,null);assert.equal(result[0].state,'unknown');
assert.equal(view([{...claude,limits:{...claude.limits,fiveHour:null}}])[0].partial,true);assert.equal(view([{...claude,limits:null}])[0].state,'unknown');
assert.deepEqual(providerUsage(null,null,now).map(p=>p.state),['unknown','unknown']);assert.deepEqual(providerUsage({accounts:'bad'},null,now).map(p=>p.state),['unknown','unknown']);
assert.equal(providerTone(0),'ok');assert.equal(providerTone(69),'ok');assert.equal(providerTone(70),'warn');assert.equal(providerTone(90),'bad');assert.equal(providerTone(null),'none');
assert.match(resetDescription({resetsAt:null},now),/not reported/);assert.match(resetDescription({resetsAt:now-1},now),/awaiting a new reading/);assert.match(resetDescription({resetsAt:now+3600000},now),/1h 0m/);
console.log('PASS: both providers, account identity, excluded foreign account, deduplication, threshold colours, stale/unknown/partial/future/reset states; no summed quotas.');
